const path=require('node:path');
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const ts=require(path.resolve(__dirname,'../node_modules/typescript'));
const records=new Map();
const DB={prepare(sql){let args;return {bind(...v){args=v;return this},async run(){if(sql.startsWith('INSERT')){let [id,owner,kind,data,created_at,updated_at]=args;records.set(id,{id,owner,kind,data,created_at,updated_at});}else if(sql.startsWith('UPDATE')){let [data,updated_at,id,owner,kind]=args;const r=records.get(id);if(r?.owner===owner&&r.kind===kind)records.set(id,{...r,data,updated_at});}else if(sql.startsWith('DELETE')){let [id,owner,kind]=args;const r=records.get(id);if(r?.owner===owner&&r.kind===kind)records.delete(id);}return {success:true}},async first(){let [id,owner,kind]=args;const r=records.get(id);return r?.owner===owner&&r.kind===kind?r:null},async all(){let [owner,kind]=args;return {results:[...records.values()].filter(x=>x.owner===owner&&x.kind===kind)}}}}};
const html='<html><title>Business A</title><body>'+('Business A shop and contact hello@business-a.example. About us. '.repeat(5))+'<a href="https://www.instagram.com/businessa/">Our Instagram</a><script type="application/ld+json">{"address":{"streetAddress":"1 Example Road","addressLocality":"Durban"}}</script></body></html>';
const rss='<rss><channel><item><title>Candidate A</title><link>https://business-a.example/</link><description>A matching candidate</description></item></channel></rss>';
const sandbox={TextEncoder,atob,btoa,exports:{},require(n){if(n==='cloudflare:workers')return {env:{SEARCH_VAULT_KEY:Buffer.alloc(32,7).toString('base64'),DB,BUCKET:{delete:async()=>{}}}};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>({userId:'owner-a',email:'donlegendwear@gmail.com'})};throw Error(n)},crypto:webcrypto,URL,AbortSignal,TextDecoder,fetch:async url=>new Response(String(url).includes('bing.com')?rss:html,{headers:{'Content-Type':'text/html'}})};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../lib/zuxuru.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,sandbox);


const pure={...sandbox,exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../lib/intelligence-view.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,pure);
const growth={...sandbox,exports:{},require(n){if(n==='./zuxuru')return sandbox.exports;if(n==='./intelligence-view')return pure.exports;throw Error(n)}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../lib/growth.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,growth);
(async()=>{const m=sandbox.exports,g=growth.exports;
const base=await m.save('owner-a','profile',{name:'Business A',searchName:'Business A',locationInput:'Durban',website:'https://business-a.example/',identityConfirmed:true,selectedEvidenceId:'website',selectedSourceUrl:'https://business-a.example/',evidence:[{id:'website',title:'Business A',url:'https://business-a.example/',state:'Retrieved'}],score:{value:25,version:'website-signals-v1',scope:'Inspected website only',sourceUrl:'https://business-a.example/',checks:[{name:'Public contact',observed:false,points:25}]} });
const edited=await g.businessDetails('owner-a',base.id,{legalName:'Business A',website:'https://business-a.example/',history:'Owner supplied history'});assert.equal(edited.details.state,'Provided by account owner · not independently verified');await assert.rejects(()=>g.businessDetails('owner-b',base.id,{}),/Permission/);
const child=await m.save('owner-a','profile',{name:'Business B',identityConfirmed:true,evidence:[{id:'child',state:'Retrieved',url:'https://business-b.example/'}],selectedEvidenceId:'child',selectedSourceUrl:'https://business-b.example/'});
await assert.rejects(()=>g.addRelationship('owner-a',{parentId:base.id,childId:base.id,relationship:'Branch',sourceUrl:'https://evidence.example/'}),/different/);
await g.addRelationship('owner-a',{parentId:base.id,childId:child.id,relationship:'Branch',sourceUrl:'https://evidence.example/'});assert.equal((await m.list('owner-a','relationship')).length,1);
const plan=await g.growthPlan('owner-a',base.id);assert.equal(plan.proposals[0].sourceUrl,'https://business-a.example/');assert.equal((await m.list('owner-a','task')).length,0);await g.approvePlan('owner-a',plan.id);await g.approvePlan('owner-a',plan.id);assert.equal((await m.list('owner-a','task')).length,1);
const measured=await g.rescore('owner-a',base.id);assert.equal(measured.measurement.comparable,true);assert.equal(measured.measurement.change,75);assert.equal((await m.list('owner-a','profile')).length,2);
assert.equal(g.comparable(measured.profile,{...measured.profile,score:{...measured.profile.score,scope:'Different'}}),false);
sandbox.fetch=async()=>new Response('unavailable',{status:503});await assert.rejects(()=>g.rescore('owner-a',base.id),/previous score is retained/);assert.equal((await m.get('owner-a','profile',base.id)).score.value,100);
const cycle=await g.runGrowthCycle('owner-a',base.id).catch(e=>e);assert.match(cycle.message,/Source Unavailable/);assert.equal((await m.list('owner-a','workflow'))[0].state,'Failed');
sandbox.fetch=async()=>new Response(JSON.stringify({results:[{title:'Business A',content:'Business A in Durban',url:'https://business-a.example/'}]}),{headers:{'Content-Type':'application/json'}});await g.connectSearx('owner-a','https://search.example/',true);assert.equal(await g.searxForOwner('owner-b'),null);assert.equal(await g.publicSearxForApp(),'https://search.example');const found=await m.investigate('Business A','Durban','',null,await g.searxForOwner('owner-a'));assert.equal(found.searchProvider,'SearXNG');assert.equal(found.evidence.length,1);assert.equal(found.sources.length,4);
console.log('PASS: profile provenance, owner isolation, relationship identity, proof-linked proposals, explicit approval, idempotent tasks, same-rubric rescore, failed-source preservation, workflow failure audit, SearXNG adapter. External APIs mocked.');})().catch(e=>{console.error(e);process.exit(1)});
