'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Search,ArrowRight,ChevronDown,Play,Network,Plug,Rocket,Target,ChartNoAxesColumnIncreasing,Menu,Loader2,ChevronRight} from 'lucide-react';
import Workspace from './workspace';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const features=[{title:'DeepSearch Engine',icon:Search,body:'Find raw public names, profiles and source links.',screen:'Investigation'},{title:'Visibility Score',icon:ChartNoAxesColumnIncreasing,body:'Review your visibility signals and evidence links.',screen:'Visibility Score'},{title:'Business Graph',icon:Network,body:'Build your profile from confirmed source matches.',screen:'Business Graph'},{title:'Connect & Unlock',icon:Plug,body:'Connect your platforms for deeper insights and control.',screen:'CIA Connect'},{title:'Autopilot Growth',icon:Rocket,body:'Run evidence checks and review proposed growth actions.',screen:'Autopilot Growth'},{title:'Rescore & Grow',icon:Target,body:'Track improvement with evidence and rescore.',screen:'Monitor'}];
export default function Appfront({signedIn,signInHref,signOutHref}:{signedIn:boolean;signInHref:string;signOutHref:string}){
 const [screen,setScreen]=useState(signedIn?'Overview':''),[profileId,setProfileId]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tour,setTour]=useState(false),[mobile,setMobile]=useState(false),[counts,setCounts]=useState<any>(null),[guest,setGuest]=useState<any>(null),[introPlaying,setIntroPlaying]=useState(false);const introVideo=useRef<HTMLVideoElement>(null),restored=useRef(false);
 useEffect(()=>{if(signedIn)fetch('/api/os',{cache:'no-store'}).then(r=>r.json()).then((d:any)=>{if(!d.error)setCounts({businesses:d.profile.length,sources:new Set(d.profile.flatMap((p:any)=>p.evidence.map((e:any)=>e.url))).size,actions:d.task.length,assets:d.asset.length});}).catch(()=>{});},[signedIn]);
 async function investigate(e:FormEvent){e.preventDefault();if(!name.trim())return;setGuest(null);setBusy(true);setError('');try{const r=await fetch(signedIn?'/api/os':'/api/public/investigate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'investigate',name:name.trim()})}),d:any=await r.json();if(!r.ok)throw Error(d.error);if(signedIn){setProfileId(d.result.id);setScreen('Profile');}else setGuest(d.result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!signedIn||restored.current)return;restored.current=true;const pending=sessionStorage.getItem('zuxuru-pending-name');if(!pending)return;sessionStorage.removeItem('zuxuru-pending-name');setBusy(true);fetch('/api/os',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'investigate',name:pending})}).then(async r=>{const j:any=await r.json();if(!r.ok)throw Error(j.error);setProfileId(j.result.id);setScreen('Profile');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[signedIn]);
 function saveGuest(){sessionStorage.setItem('zuxuru-pending-name',guest.name);window.location.assign(signInHref);}
 function open(section:string){setScreen(section);setMobile(false);}
 if(screen)return <Workspace signedIn={signedIn} signInHref={signInHref} signOutHref={signOutHref} initialView={screen} initialProfileId={profileId}/>;
 return <div className="zuxuru-front"><div className="zf-announcement"><span>NEW</span><p>Zuxuru <b>Autopilot</b> — Your visibility, growth and content in one place.</p><button onClick={()=>open('Autopilot Growth')}>Learn more <ArrowRight size={15}/></button><ChevronRight size={16} className="zf-announcement-end"/></div>
 <header className="zf-header"><a className="zf-logo" href="/" aria-label="Zuxuru home"><span className="zf-brand-mark"><img src="/zuxuru-reference.png" alt=""/></span><strong>ZUXURU</strong></a><nav className={mobile?'zf-nav is-open':'zf-nav'} aria-label="Main navigation">{[{title:'Product',items:[['Business dashboard','Overview'],['Business investigation','Investigation'],['Business profile','Profile'],['Visibility score','Visibility Score'],['Business graph','Business Graph'],['CIA connections','CIA Connect'],['Studio','Studio']]},{title:'Solutions',items:[['Business intelligence','Intelligence'],['Growth opportunities','Opportunities'],['Lead management','Leads'],['Business monitoring','Monitor']]}].map(m=><DropdownMenu key={m.title}><DropdownMenuTrigger className="zf-nav-button">{m.title}<ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent>{m.items.map(([label,target])=><DropdownMenuItem key={label} onClick={()=>open(target)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>)}<button className="zf-nav-button" onClick={()=>open('Packages')}>Pricing</button><DropdownMenu><DropdownMenuTrigger className="zf-nav-button">Resources <ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onClick={()=>setTour(true)}>How Zuxuru works</DropdownMenuItem><DropdownMenuItem onClick={()=>open('Profile')}>Evidence & source links</DropdownMenuItem><DropdownMenuItem onClick={()=>open('Monitor')}>Results & rescore</DropdownMenuItem></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger className="zf-nav-button">Company <ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onClick={()=>setTour(true)}>Zuxuru by Bysei</DropdownMenuItem><DropdownMenuItem onClick={()=>open('Overview')}>Open Zuxuru app</DropdownMenuItem></DropdownMenuContent></DropdownMenu></nav><div className="zf-account">{signedIn?<button onClick={()=>open('Overview')}>My business</button>:<a href={signInHref} target="_top">Log in</a>}<button className="zf-gradient zf-start" onClick={()=>document.getElementById('business-name')?.focus()}>Start Free</button><button className="zf-mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu/></button></div></header>
 <div className="zf-hero"><section className="zf-intro"><span className="zf-badge">AI-POWERED BUSINESS VISIBILITY PLATFORM</span><h1>Be Found.<br/>Be Chosen.<br/>Be <em>Alive</em> with Zuxuru.</h1><p className="zf-description">Zuxuru investigates your digital presence, reveals the evidence behind your visibility, and shows you what to improve, create and measure online.</p><form className="zf-search" onSubmit={investigate}><Search size={20}/><input id="business-name" aria-label="Business name" value={name} onChange={e=>setName(e.target.value)} required maxLength={180} placeholder="Enter your business name to check your visibility"/><button className="zf-gradient" disabled={busy}>{busy?<><Loader2 className="spin" size={18}/>Investigating…</>:<>Check My Score <ArrowRight size={18}/></>}</button></form><div className="zf-search-caption"><small>Free public investigation. No signup required. Review raw matches first.</small><button onClick={()=>setTour(true)}><Play size={13}/> How it works <ChevronRight size={14}/></button></div>{error&&<p className="zf-error" role="alert">{error}</p>}</section>
 <section className="zf-presentation" aria-label="Zuxuru introduction"><div className="zf-video" style={{position:'relative'}}><video ref={introVideo} controls playsInline preload="metadata" poster="/zuxuru-city.png" onPlay={()=>setIntroPlaying(true)} onPause={()=>setIntroPlaying(false)} style={{display:'block',width:'100%',height:'100%',objectFit:'cover'}}><source src="/zuxuru-introduction.mp4" type="video/mp4"/><track src="/zuxuru-introduction.vtt" kind="captions" srcLang="en" label="English" default/></video>{!introPlaying&&<><div className="zf-video-title" style={{pointerEvents:'none'}}><strong>ZUXURU</strong><span>Your Business. Everywhere.</span><b>Alive.</b></div><button className="zf-play" aria-label="Play the Zuxuru introduction video" onClick={()=>introVideo.current?.play().catch(()=>setTour(true))}><Play fill="currentColor" size={34}/></button></>}</div><div className="zf-video-caption"><Rocket size={21}/><span>See how Zuxuru makes your business visible, credible and chosen.</span></div></section></div>
 {guest&&<section className="zf-public-results" aria-live="polite"><div className="section-heading"><div><span className="pill">FBL / RAW PUBLIC RESULTS</span><h2>Results for “{guest.name}”</h2></div><button className="zf-gradient" onClick={saveGuest}>Sign in to save and confirm your business</button></div><p>These are name-matching candidates. Similar names may represent different businesses.</p>{guest.evidence.length?guest.evidence.map((e:any)=><div className="evidence" key={e.id}><small>{e.platform} · {e.state}</small><h3>{e.title}</h3><a href={e.url} target="_blank" rel="noreferrer">{e.url}</a><p>{e.excerpt}</p></div>):<p>No matching public evidence returned. A working search server is needed for wider investigation. No identity or score has been invented.</p>}{guest.sources.map((source:any,i:number)=><p key={i}>{source.status} · <a href={source.url} target="_blank" rel="noreferrer">Search evidence</a></p>)}</section>}
 <section className="zf-signals"><div className="zf-platforms"><p>Investigate your business across public sources</p><div><span>Google</span><span className="zf-meta">Meta <small>Facebook · Instagram</small></span><span>Web <small>Public websites</small></span><span>Directories <small>Business sources</small></span></div></div><div className="zf-metrics">{[['Businesses saved',counts?.businesses],['Evidence links',counts?.sources],['Growth actions',counts?.actions],['Studio assets',counts?.assets]].map(([title,value])=><div key={title}><strong>{value??'—'}</strong><span>{title}</span></div>)}</div></section>
 <section className="zf-features" aria-label="Zuxuru operating flow">{features.map(({title,icon:Icon,body,screen})=><button key={title} onClick={()=>open(screen)}><span className="zf-feature-icon"><Icon size={38} strokeWidth={1.7}/></span><strong>{title} <ChevronRight size={15}/></strong><p>{body}</p></button>)}</section><footer className="zf-footer">Zuxuru by Bysei <button onClick={()=>open('Overview')}>Open your Zuxuru app <ArrowRight size={14}/></button></footer>
 <Dialog open={tour} onOpenChange={setTour}><DialogContent className="zf-tour" onCloseAutoFocus={e=>{e.preventDefault();document.getElementById('business-name')?.focus();}}><DialogHeader><DialogTitle>Your Business. Everywhere. Alive.</DialogTitle><DialogDescription>Zuxuru by Bysei — start with evidence, then take action.</DialogDescription></DialogHeader><ol><li><strong>Investigate your business name</strong><p>Review raw public names, page titles and source links. Select the correct match.</p></li><li><strong>Build your evidence profile</strong><p>Confirm identity and review the scope and proof behind each measured signal.</p></li><li><strong>Connect through CIA</strong><p>Use evidence links to find the correct account. External actions require authorization.</p></li><li><strong>Create, deliver and rescore</strong><p>Save growth plans and Studio assets. Track completed actions and compare investigations.</p></li></ol><button className="zf-gradient" onClick={()=>{setTour(false);document.getElementById('business-name')?.focus();}}>Start with your business name <ArrowRight size={16}/></button></DialogContent></Dialog>
 </div>;
}
