'use client';
import {Building2,MapPin,Phone,ArrowUpRight,Clapperboard,Link2,Lightbulb,Users,Activity,BrainCircuit,CheckCircle2,Clock3} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {businessIntelligence} from '@/lib/intelligence-view';

export default function BusinessDashboard({profile,data,navigate,connect}:{profile:any;data:any;navigate:(view:string)=>void;connect:(e:any)=>void}){
 const analysis=profile?businessIntelligence(profile):null;
 const tasks=data.task.filter((t:any)=>t.profileId===profile?.id),assets=data.asset.filter((a:any)=>a.profileId===profile?.id),history=data.history.filter((h:any)=>h.profileId===profile?.id),measurements=data.measurement.filter((m:any)=>m.profileId===profile?.id);
 const score=analysis?.score,latest=measurements[0];
 const setup=[['Identity',Boolean(profile?.identityConfirmed)],['Business details',Boolean(profile?.details?.legalName)],['Location & contact',Boolean(profile?.physicalLocation&&profile?.contacts?.length)],['Website evidence',Boolean(score)],['Platform authorization',Boolean(data.postiz?.configured)],['Approved plan',data.package.some((p:any)=>p.profileId===profile?.id&&p.approval==='Approved')]];
 const cards=[['Branding','Intelligence',BrainCircuit],['Marketing','Intelligence',Lightbulb],['Leads','Leads',Users],['Packages','Packages',Building2],['Delivery','Monitor',ArrowUpRight],['Analytics','Monitor',Activity],['Automation','Autopilot Growth',Clock3],['Studio','Studio',Clapperboard]] as const;
 return <div className="business-station">
  <section className="panel station-hero"><div className="station-business"><div className="station-avatar">{profile?.name?.slice(0,1)||<Building2/>}</div><div><span className="pill">{profile?.identityConfirmed?'Identity confirmed by owner':'Identity review needed'}</span><h2>{profile?.details?.legalName||profile?.name||'Your business visibility station'}</h2><p>{profile?.details?.industry||'Investigate a business to build its profile'}</p><p><MapPin size={14}/>{profile?.physicalLocation?.value||profile?.locationInput||'Location unknown'}</p><p><Phone size={14}/>{profile?.contacts?.join(' · ')||'Contact evidence unknown'}</p><button className="secondary" onClick={()=>navigate(profile?'Business Graph':'Investigation')}>{profile?'Edit business profile':'Investigate my business'} <ArrowUpRight size={14}/></button></div></div><div className="station-score"><div className="score-orbit" style={{'--score-deg':`${(score?.value||0)*3.6}deg`} as any}><div><strong>{score?.value??'—'}</strong><small>{score?'/ 100':'Unmeasured'}</small></div></div><div><h3>Visibility evidence</h3><p>{score?'Website signals · provisional':'Confirm identity and inspect a website'}</p><small>{latest?.comparable?`${latest.change>0?'+':''}${latest.change} points · comparable rescore`:'No verified growth delta'}</small><button className="secondary" onClick={()=>navigate('Visibility Score')}>View score & proof</button></div></div></section>
  <section className="panel station-setup"><div className="section-heading"><h3>Full business setup</h3><button className="secondary" onClick={()=>navigate('Business Graph')}>View setup details</button></div><div className="setup-track">{setup.map(([name,complete])=><div key={String(name)} className={complete?'done':''}><CheckCircle2 size={21}/><span>{name}</span><small>{complete?'Recorded':'Needs evidence'}</small></div>)}</div><small>Saved authorization metadata is not proof of current platform access. Check live channels in CIA.</small></section>
  <div className="station-grid"><section className="panel"><h3>Business overview</h3><p>{profile?.details?.history||'Your business history, products and identity evidence will appear here.'}</p><div className="stats"><div><small>Evidence links</small><strong className="stat">{profile?.evidence?.length??'—'}</strong></div><div><small>Studio assets</small><strong className="stat">{profile?assets.length:'—'}</strong></div><div><small>Pending actions</small><strong className="stat">{profile?tasks.filter((t:any)=>t.state==='Pending').length:'—'}</strong></div></div><button className="secondary" onClick={()=>navigate('Profile')}>Review identity & evidence</button></section>
   <section className="panel"><div className="section-heading"><h3>Platform profiles</h3><button className="text-button" onClick={()=>navigate('CIA Connect')}>View all</button></div>{(analysis?.platforms||[{name:'Google Business',evidence:[]},{name:'Facebook',evidence:[]},{name:'Instagram',evidence:[]},{name:'Website',evidence:[]}]).slice(0,7).map((p:any)=><div className="platform-row" key={p.name}><div><strong>{p.name}</strong><small>{p.evidence.length?`${p.evidence.length} public links · review ownership`:'Unknown · no evidence'}</small></div><button className="text-button" onClick={()=>p.evidence[0]?connect({...p.evidence[0],businessId:profile.id}):navigate('CIA Connect')}>{p.evidence.length?'Review / connect':'Connect'} <Link2 size={13}/></button></div>)}</section>
   <section className="panel"><h3>Visibility breakdown</h3>{score?score.checks.map((c:any)=><div className="signal-row" key={c.name}><div><span>{c.name}</span><strong>{c.observed?c.points:0} / {c.points}</strong></div><Progress value={c.observed?100:0}/><small>{c.observed?'Observed on inspected page':'Not observed on inspected page'}</small></div>):<p>Website checks appear after an evidence-backed investigation. Search, reviews and social performance are unknown until measured.</p>}<button className="secondary" onClick={()=>navigate('Intelligence')}>Review findings</button></section>
  </div>
  <div className="station-grid"><section className="panel"><h3>Business growth station</h3><p>Turn evidence into reviewed work.</p><div className="station-actions">{cards.map(([title,view,Icon])=><button className="station-action" key={title} onClick={()=>navigate(view)}><Icon size={22}/><strong>{title}</strong><ArrowUpRight size={14}/></button>)}</div></section><section className="panel"><h3>Zuxuru Digital Studio</h3><p>Create → Capture → Edit → Approve → Publish → Measure</p><div className="studio-steps"><span>Create</span><span>Record</span><span>Edit</span><span>Publish</span></div><div className="station-actions"><button className="station-action" onClick={()=>navigate('Intelligence')}><BrainCircuit/><strong>Creative brief</strong></button><button className="station-action" onClick={()=>navigate('Studio')}><Clapperboard/><strong>Camera & recording</strong></button></div><button className="primary" onClick={()=>navigate('Studio')}>Open Studio <ArrowUpRight size={15}/></button><small>{data.ai?.configured?'Gateway configured · run to verify generation':'AI generation needs CIA authorization'}</small></section><section className="panel"><h3>Business history & activity</h3>{history.length?history.slice(0,5).map((h:any)=><div className="activity-item" key={h.id}><i/><div><strong>{h.action}</strong><small>{new Date(h.createdAt).toLocaleString()} · {h.actor}</small></div></div>):<p>Investigations, approvals, AI runs and measured results are recorded here. No activity has been assumed.</p>}<button className="secondary" onClick={()=>navigate('Business Graph')}>View full history</button></section></div>
 </div>;
}
