'use client';
import {useState} from 'react';
import {businessIntelligence} from '@/lib/intelligence-view';
export default function IntelligencePanel({profile,data,action,studio,connect}:{profile:any;data:any;action:(name:string,body?:any)=>Promise<any>;studio:(draft:any)=>void;connect:()=>void}){
 const [task,setTask]=useState('Visibility diagnosis'),[consent,setConsent]=useState(false);
 if(!profile)return <section className="panel"><h2>Business intelligence</h2><p>Investigate your business and confirm its identity to begin.</p></section>;
 const current=businessIntelligence(profile),runs=data.agent_run.filter((r:any)=>r.profileId===profile.id),reviews=data.intelligence.filter((r:any)=>r.profileId===profile.id);
 return <><section className="panel"><span className="pill">EVIDENCE → INTELLIGENCE</span><h2>{profile.name}</h2><p>{current.state} · {current.scope}</p><div className="buttons"><button className="primary" disabled={!profile.identityConfirmed} onClick={()=>action('intelligence_analyze',{id:profile.id})}>Run evidence analysis</button><button className="secondary" onClick={connect}>Connect deeper sources</button></div><small>Priority = Impact × Confidence × Business relevance ÷ Effort. Values are transparent planning heuristics, not performance predictions.</small></section>
 <div className="grid"><section className="panel"><h3>Observed website findings</h3>{current.findings.length?current.findings.map((f:any)=><div className="evidence" key={f.id}><strong>{f.title}</strong><p>{f.state}{f.stale?' · Stale':''}</p><p>{f.observation}</p><a href={f.sourceUrl} target="_blank" rel="noreferrer">Source proof ↗</a><small>{f.retrievedAt} · {f.scope}</small></div>):<p>No confirmed website findings yet. Unknown sources do not count as zero.</p>}</section><section className="panel"><h3>Prioritized growth opportunities</h3>{current.opportunities.length?current.opportunities.map((o:any)=><div className="evidence" key={o.id}><strong>{o.title}</strong><span className="pill">Priority {o.priority}</span><p>Impact {o.impact}/5 · Confidence {o.confidence} · Relevance {o.relevance}/5 · Effort {o.effort}</p><p>{o.basis}</p><a href={o.sourceUrl} target="_blank" rel="noreferrer">Evidence behind this opportunity</a></div>):<p>Run an investigation first. No missing social profile is inferred from an unavailable search.</p>}<small>{reviews.length} saved evidence reviews · latest {reviews[0]?.analyzedAt||'None'}</small></section></div>
 <section className="panel"><span className="pill">AI ANALYSIS · REVIEW REQUIRED</span><h2>Business analyst</h2><p>Ask for diagnosis, branding, marketing or a Studio brief using your saved evidence. AI cannot change your score or publish to your accounts.</p><p>{data.ai?.status||'Disconnected'} · {data.ai?.model||'No model connected'}</p><form onSubmit={async e=>{e.preventDefault();await action('ai_analyze',{id:profile.id,task,consent});}}><label>Analysis task<select value={task} onChange={e=>{setTask(e.target.value);setConsent(false);}}>{['Visibility diagnosis','Brand strategy','Marketing strategy','Studio creative brief'].map(x=><option key={x}>{x}</option>)}</select></label><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this business name, industry, products and public evidence to my configured AI gateway for this task.</label><button className="primary" disabled={!data.ai?.configured||!profile.identityConfirmed||!consent}>Run AI analysis</button>{!data.ai?.configured&&<button type="button" className="secondary" onClick={connect}>Connect AI in CIA</button>}</form></section>
 {runs.map((r:any)=><section className="panel" key={r.id}><span className="pill">{r.state}</span><h3>{r.title}</h3><small>{r.model} · {r.startedAt} · no external execution permission</small>{r.error&&<p className="alert">{r.error}</p>}{r.output&&<><p className="prewrap">{r.output.summary}</p>{r.output.recommendations.map((o:any,i:number)=><div className="evidence" key={i}><strong>{o.title}</strong><p>{o.reason}</p><small>{o.state} · {o.grounding}</small>{o.sourceLinks.map((url:string)=><a className="proof-link" key={url} href={url} target="_blank" rel="noreferrer">Supplied evidence ↗</a>)}{o.content&&<><p className="prewrap">{o.content}</p><button className="secondary" onClick={()=>studio({title:o.title,content:o.content,profileId:profile.id,approved:false,state:'Draft'})}>Review draft in Studio</button></>}</div>)}</>}</section>)}</>;
}
