'use client';
import {useEffect,useRef,useState} from 'react';
export default function StudioCapture({onCapture,onError}:{onCapture:(data:{fileData:string;mime:string})=>void;onError:(error:string)=>void}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [mode,setMode]=useState(''),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0);
 function close(){if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearTimeout(timer.current);setRecording(false);setMode('');}
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(!recording)return;const t=setInterval(()=>setElapsed(n=>n+1),1000);return()=>clearInterval(t);},[recording]);
 async function open(type:string){try{close();if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera and microphone are unavailable in this browser.');const s=await navigator.mediaDevices.getUserMedia({video:type!=='audio'?{facingMode:'environment',width:{ideal:640},height:{ideal:360}}:false,audio:type!=='photo'});stream.current=s;setMode(type);setElapsed(0);if(video.current){video.current.srcObject=s;await video.current.play();}}catch(e){onError((e as Error).message);}}
 function file(blob:Blob){if(blob.size>2000000){onError('Capture exceeds 2 MB. Record a shorter clip.');return;}const reader=new FileReader();reader.onload=()=>onCapture({fileData:String(reader.result).split(',')[1],mime:blob.type.split(';')[0]});reader.readAsDataURL(blob);}
 function photo(){if(!video.current||!video.current.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;canvas.getContext('2d')?.drawImage(video.current,0,0);canvas.toBlob(blob=>{if(blob)file(blob);close();},'image/jpeg',0.85);}
 function record(){try{if(!stream.current)throw Error('Open camera or microphone first.');const mime=mode==='audio'?'audio/webm':'video/webm';if(!window.MediaRecorder||!MediaRecorder.isTypeSupported(mime))throw Error('Recording is unavailable here. Use the upload/capture input instead.');const pieces:BlobPart[]=[];const r=new MediaRecorder(stream.current,{mimeType:mime,videoBitsPerSecond:400000,audioBitsPerSecond:64000});recorder.current=r;r.ondataavailable=e=>{if(e.data.size)pieces.push(e.data);};r.onstop=()=>{file(new Blob(pieces,{type:mime}));stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRecording(false);setMode('');if(timer.current)clearTimeout(timer.current);};r.start();setRecording(true);setElapsed(0);timer.current=setTimeout(()=>r.state==='recording'&&r.stop(),20000);}catch(e){onError((e as Error).message);}}
 return <section className="panel"><span className="pill">STUDIO CAPTURE</span><h2>Record on your device</h2><div className="buttons"><button type="button" className="secondary" onClick={()=>open('photo')}>Open camera for photo</button><button type="button" className="secondary" onClick={()=>open('video')}>Open video camera</button><button type="button" className="secondary" onClick={()=>open('audio')}>Open microphone</button></div><video ref={video} autoPlay playsInline muted style={{display:mode&&mode!=='audio'?'block':'none',width:'100%',maxHeight:360}}/>{mode&&<><p>{recording?'Recording: '+elapsed+' seconds':'Device ready'} · clips stop after 20 seconds</p><div className="buttons">{mode==='photo'?<button type="button" className="primary" onClick={photo}>Capture photo</button>:recording?<button type="button" className="primary" onClick={()=>recorder.current?.stop()}>Stop recording</button>:<button type="button" className="primary" onClick={record}>Start recording</button>}<button type="button" className="secondary" onClick={close}>Close device</button></div></>}<small>Captures attach to the current draft. Review and save the asset below. Device access requires your browser’s permission.</small></section>;
}
