import assert from 'node:assert/strict';
import {planFashionWork,fashionModules,designerEngine} from '../worker/designer-engine.mjs';
const payload={'zuxuru-fashion-service-v1':{designer:{name:'Studio',story:'Fashion'},products:[{id:'p',name:'Dress',price:null}],evidence:[],orders:[{id:'o',customer:'Client',stage:'Quote',next:'Confirm fit',due:'2026-01-01'}]},'zuxuru-designer-work-v1':{tasks:[],studio:[]}};
const actions=planFashionWork(payload);assert.equal(actions.length,8);assert.deepEqual(new Set(actions.map(a=>a.area)),new Set(fashionModules.map(m=>m[0])));assert(actions.some(a=>a.area==='sales'&&a.deliverable==='Confirm fit'));assert(actions.some(a=>a.area==='products'&&a.title.includes('full costing')));let written;const DB={prepare(sql){return{bind(...args){this.args=args;this.sql=sql;return this;},first:async()=>({payload:JSON.stringify(payload),revision:4})}},batch:async statements=>{written=JSON.parse(statements[0].args[0]);return[{meta:{changes:1}},{meta:{changes:1}}]}};
const request=new Request('https://site.test/api/designer/engine',{method:'POST',headers:{origin:'https://site.test','oai-authenticated-user-id':'a'}});const response=await designerEngine(request,{DB});assert.equal(response.status,200);assert.equal(written['zuxuru-designer-work-v1'].tasks.length,8);const report=await response.json();assert.equal(report.mode,'saved-record-rules');const after=written;const DB2={...DB,prepare(sql){const stmt=DB.prepare(sql);stmt.first=async()=>({payload:JSON.stringify(after),revision:5});return stmt;}};const rerun=await(await designerEngine(request,{DB:DB2})).json();assert.equal(rerun.added,0);assert(rerun.actions.every(a=>a.status==='Already in work queue'));console.log('PASS eight-module routing, real record evidence, cloud task assignment and rerun deduplication');

const prioritized=structuredClone(payload);prioritized['zuxuru-fashion-service-v1'].orders=[{id:'later',customer:'Later',stage:'Enquiry',due:'2026-12-01'},{id:'first',customer:'First',stage:'Quote',due:'2026-01-01'},{id:'delivered',customer:'Delivered',stage:'Delivered',due:'2020-01-01'}];const chosen=planFashionWork(prioritized).find(a=>a.area==='sales');assert.match(chosen.title,/First/);assert.equal(chosen.due,'2026-01-01');const {fashionTargetDate,selectOpenFashionOrder,selectUncostedFashionProduct}=await import('../worker/fashion-record-decisions.mjs');assert.equal(fashionTargetDate('2026-02-31'),'');assert.equal(selectOpenFashionOrder([{stage:'Enquiry',due:''},{stage:'Enquiry',due:'2026-02-01',id:'dated'}]).id,'dated');assert.equal(prioritized['zuxuru-fashion-service-v1'].orders[0].id,'later');const costed={materials:10,labour:10,production:0,packCost:0,delivery:0,other:0,price:50};assert.equal(selectUncostedFashionProduct([costed]),undefined);assert(selectUncostedFashionProduct([{...costed,delivery:-1}]));assert(selectUncostedFashionProduct([{...costed,price:0}]));console.log('PASS shared backend decisions: earliest open deadline, invalid calendar dates, immutable records, confirmed zeros and negative/zero-price costing checks.');

const changed=structuredClone(after);changed['zuxuru-fashion-service-v1'].orders[0].due='2026-03-01';const DB3={...DB,prepare(sql){const stmt=DB.prepare(sql);stmt.first=async()=>({payload:JSON.stringify(changed),revision:6});return stmt;}};const changedRun=await(await designerEngine(request,{DB:DB3})).json();assert.equal(changedRun.added,0);assert.equal(written['zuxuru-designer-work-v1'].tasks.find(t=>t.area==='sales').due,'2026-03-01');assert(changedRun.actions.some(a=>a.status==='Customer deadline updated'));changed['zuxuru-designer-work-v1'].tasks.find(t=>t.area==='sales').due='2026-04-01';await designerEngine(request,{DB:DB3});assert.equal(written['zuxuru-designer-work-v1'].tasks.find(t=>t.area==='sales').due,'2026-04-01');console.log('PASS generated task deadline refresh: no duplicate tasks and manually edited dates preserved.');

const full=structuredClone(after);for(let i=full['zuxuru-designer-work-v1'].tasks.length;i<500;i++)full['zuxuru-designer-work-v1'].tasks.push({id:'filler-'+i,title:'Extra '+i,area:'career',done:false});const capacityDB=value=>({...DB,prepare(sql){const stmt=DB.prepare(sql);stmt.first=async()=>({payload:JSON.stringify(value),revision:10});return stmt;}});const fullRun=await designerEngine(request,{DB:capacityDB(full)});assert.equal(fullRun.status,200);assert.equal((await fullRun.json()).added,0);const tight=structuredClone(payload);tight['zuxuru-designer-work-v1'].tasks=Array.from({length:493},(_,i)=>({id:'other-'+i,title:'Other '+i,area:'career',done:false}));const beforeCapacity=JSON.stringify(written);const refused=await designerEngine(request,{DB:capacityDB(tight)});assert.equal(refused.status,409);const refusal=await refused.json();assert.equal(refusal.required,8);assert.equal(refusal.available,7);assert.equal(JSON.stringify(written),beforeCapacity);console.log('PASS queue capacity: 500-task reruns remain available; insufficient new-task capacity rejects atomically with exact slot counts.');
