import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {digitalStudio} from '../worker/digital-studio.mjs';
import {businessBook} from '../worker/business-book.mjs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../drizzle/0005_elite_ken_ellis.sql',import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};},async batch(list){sqlite.exec('BEGIN');try{const result=[];for(const query of list)result.push(await query.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const req=(path,method='GET',body,user='owner',token)=>new Request('https://studio.test'+path,{method,headers:{origin:'https://studio.test','content-type':'application/json',...(user?{'oai-authenticated-user-id':user}:{}),...(token?{'x-studio-token':token}:{})},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await digitalStudio(req('/api/studio/rooms','POST',null,null),{DB})).status,401);
const response=await digitalStudio(req('/api/studio/rooms','POST'),{DB});assert.equal(response.status,201);const room=await response.json();assert.equal(room.links.length,5);const databaseRoom=sqlite.prepare('SELECT * FROM studio_rooms').get();
for(let slot=1;slot<=5;slot++){const p=new URLSearchParams(new URL(room.links[slot-1]).hash.slice(1)),token=p.get('token');assert(!databaseRoom.tokens.includes(token));const path='/api/studio/rooms/'+room.id+'/signals?slot='+slot;assert.equal((await digitalStudio(req(path,'POST',{event:{type:'offer',sdp:'test offer '+slot}},null,token),{DB})).status,200);assert.equal((await digitalStudio(req(path,'POST',{event:{type:'answer',sdp:'bad'}},null,token),{DB})).status,400);await digitalStudio(req(path,'POST',{slot,event:{type:'answer',sdp:'test answer '+slot}}),{DB});const inbox=await (await digitalStudio(req(path,'GET',null,null,token),{DB})).json();assert.equal(inbox.events.length,1);assert.equal(inbox.events[0].slot,slot);assert.equal((await digitalStudio(req(path.replace('slot='+slot,'slot=6'),'GET',null,null,token),{DB})).status,403);}
const hostEvents=await (await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals'),{DB})).json();assert.equal(hostEvents.events.length,5);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals','GET',null,'other-owner'),{DB})).status,403);
assert.equal((await businessBook(req('/api/designer/business-book','POST',{kind:'company',payload:{name:'Bonga Bhengu',description:'Fashion design'}}),{DB})).status,200);assert.equal((await (await businessBook(req('/api/designer/business-book'),{DB})).json()).records.length,1);assert.equal((await (await businessBook(req('/api/designer/business-book','GET',null,'other-owner'),{DB})).json()).records.length,0);
await digitalStudio(req('/api/studio/rooms/'+room.id,'DELETE'),{DB});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_signals').get().n,0);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id),{DB})).status,410);
console.log('PASS: five camera invitations, hashed secrets, isolated phone/host signaling, ownership, company persistence, and session cleanup on SQLite. Hardware camera/recording tests still require real devices.');
