import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {digitalStudio} from '../worker/digital-studio.mjs';
import {businessBook} from '../worker/business-book.mjs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../drizzle/0005_elite_ken_ellis.sql',import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};},async batch(list){sqlite.exec('BEGIN');try{const result=[];for(const query of list)result.push(await query.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const req=(path,method='GET',body,user='owner',token)=>new Request('https://studio.test'+path,{method,headers:{origin:'https://studio.test','content-type':'application/json',...(user?{'oai-authenticated-user-id':user}:{}),...(token?{'x-studio-token':token}:{})},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await digitalStudio(req('/api/studio/rooms','POST',null,null),{DB})).status,401);
const response=await digitalStudio(req('/api/studio/rooms','POST'),{DB});assert.equal(response.status,201);const room=await response.json();assert.equal(room.links.length,5);const databaseRoom=sqlite.prepare('SELECT * FROM studio_rooms').get();
for(let slot=1;slot<=5;slot++){const p=new URLSearchParams(new URL(room.links[slot-1]).hash.slice(1)),token=p.get('token');assert(!databaseRoom.tokens.includes(token));const path='/api/studio/rooms/'+room.id+'/signals?slot='+slot;assert.equal((await digitalStudio(req(path,'POST',{event:{type:'offer',sdp:'test offer '+slot}},null,token),{DB})).status,200);assert.equal((await digitalStudio(req(path,'POST',{event:{type:'answer',sdp:'bad'}},null,token),{DB})).status,400);await digitalStudio(req(path,'POST',{slot,event:{type:'answer',sdp:'test answer '+slot}}),{DB});const inbox=await (await digitalStudio(req(path,'GET',null,null,token),{DB})).json();assert.equal(inbox.events.length,1);assert.equal(inbox.events[0].slot,slot);assert.equal((await digitalStudio(req(path.replace('slot='+slot,'slot=6'),'GET',null,null,token),{DB})).status,403);}
const hostEvents=await (await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals'),{DB})).json();assert.equal(hostEvents.events.length,5);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals','GET',null,'other-owner'),{DB})).status,403);
assert.equal((await businessBook(req('/api/designer/business-book','POST',{kind:'company',payload:{name:'Bonga Bhengu',description:'Fashion design'}}),{DB})).status,200);assert.equal((await (await businessBook(req('/api/designer/business-book'),{DB})).json()).records.length,1);assert.equal((await (await businessBook(req('/api/designer/business-book','GET',null,'other-owner'),{DB})).json()).records.length,0);
await digitalStudio(req('/api/studio/rooms/'+room.id,'DELETE'),{DB});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_signals').get().n,0);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id),{DB})).status,410);
console.log('PASS: five camera invitations, hashed secrets, isolated phone/host signaling, ownership, company persistence, and session cleanup on SQLite. Hardware camera/recording tests still require real devices.');

const vm=await import('node:vm');const phoneElements={};for(const id of ['phone-status','phone-preview','phone-start','phone-stop','phone-facing','phone-audio','phone-title'])phoneElements[id]={value:'environment',checked:false};
const cameraTracks=[];const cameraPeers=[];let releaseCamera=null,cameraDelayed=false,pendingPoll,firstPoll=true;const outgoing=[];
const phoneContext={document:{getElementById:id=>phoneElements[id]},location:{hash:'#room=room&slot=1&token=token'},URLSearchParams,window:{RTCPeerConnection:true,addEventListener(){}},navigator:{mediaDevices:{getUserMedia:async()=>{const track={stop(){this.stopped=true;}};cameraTracks.push(track);const stream={getTracks:()=>[track]};if(cameraDelayed)return new Promise(resolve=>releaseCamera=()=>resolve(stream));return stream;}}},RTCPeerConnection:class{constructor(){this.connectionState='new';cameraPeers.push(this);}addTrack(){}async createOffer(){return {sdp:'offer'};}async setLocalDescription(){}close(){this.closed=true;this.connectionState='closed';this.onconnectionstatechange?.();}},setTimeout:()=>1,clearTimeout(){},fetch:async(url,options)=>{if(options.method==='POST'){outgoing.push(JSON.parse(options.body).event);return {ok:true,json:async()=>({sent:true})};}if(firstPoll){firstPoll=false;return {ok:true,json:async()=>({events:[]})};}return new Promise(resolve=>pendingPoll=()=>resolve({ok:true,json:async()=>({events:[]})}));}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/phone-camera.js',import.meta.url),'utf8'),phoneContext);
await phoneElements['phone-start'].onclick();assert.equal(outgoing[0].type,'offer');const firstPhonePeer=cameraPeers[0];firstPhonePeer.connectionState='failed';firstPhonePeer.onconnectionstatechange();assert.equal(cameraTracks[0].stopped,true);assert.equal(phoneElements['phone-start'].disabled,false);assert.match(phoneElements['phone-status'].textContent,/Reconnect/);
firstPhonePeer.connectionState='connected';firstPhonePeer.onconnectionstatechange();assert.match(phoneElements['phone-status'].textContent,/failed/);pendingPoll();await new Promise(resolve=>setImmediate(resolve));
// Cancel while permission/camera acquisition is pending: late media must be stopped.
phoneContext.fetch=async(url,options)=>({ok:true,json:async()=>({events:[],sent:true})});cameraDelayed=true;const startingPhone=phoneElements['phone-start'].onclick();await new Promise(resolve=>setImmediate(resolve));assert(releaseCamera);await phoneElements['phone-stop'].onclick();releaseCamera();await startingPhone;assert.equal(cameraTracks[1].stopped,true);assert.equal(cameraPeers.length,1);assert.equal(phoneElements['phone-preview'].srcObject,null);
console.log('PASS phone recovery: failed connections release camera, permit reconnect, ignore obsolete callbacks, and stop late camera acquisition after cancellation.');

const localCameraSource=fs.readFileSync(new URL('../dist/digital-studio.js',import.meta.url),'utf8').split('function stopLocal()')[1].split('function stopScreen()')[0];
const localButtons={'studio-local':{},'studio-local-stop':{}};let finishLocal,finishPlayback;const localTracks=[];
const localContext={localGeneration:0,local:null,videos:new Map(),streams:new Map([[1,{phone:true}]]),active:0,nextCamera:0,$:id=>localButtons[id],select(){},say(){},navigator:{mediaDevices:{getUserMedia:()=>new Promise(resolve=>finishLocal=()=>{const track={stop(){this.stopped=true;}};localTracks.push(track);resolve({getTracks:()=>[track],getVideoTracks:()=>[track]});})}},document:{createElement:()=>({pause(){this.paused=true;},play:()=>new Promise(resolve=>finishPlayback=resolve)})}};
vm.runInNewContext('function stopLocal()'+localCameraSource,localContext);
const localStarting=localButtons['studio-local'].onclick();localButtons['studio-local-stop'].onclick();finishLocal();await localStarting;assert.equal(localTracks[0].stopped,true);assert.equal(localContext.streams.has(0),false);assert.equal(localContext.streams.has(1),true);
const secondLocalStart=localButtons['studio-local'].onclick();finishLocal();await new Promise(resolve=>setImmediate(resolve));localButtons['studio-local-stop'].onclick();finishPlayback();await secondLocalStart;assert.equal(localTracks[1].stopped,true);assert.equal(localContext.streams.has(0),false);
const thirdLocalStart=localButtons['studio-local'].onclick();finishLocal();await new Promise(resolve=>setImmediate(resolve));finishPlayback();await thirdLocalStart;assert.equal(localContext.streams.has(0),true);localTracks[2].onended();assert.equal(localContext.streams.has(0),false);assert.equal(localButtons['studio-local'].disabled,false);assert.equal(localContext.streams.has(1),true);
console.log('PASS local camera stop: cancels permission and playback races, releases tracks, recovers ended tracks and preserves phone sources.');

const microphoneSource=fs.readFileSync(new URL('../dist/digital-studio.js',import.meta.url),'utf8').split('function stopMicrophone()')[1].split("$('studio-mic').onclick")[0];
const micButtons={'studio-mic':{},'studio-mic-stop':{}};let releaseMic;const micTracks=[],recordedMicTrack={stop(){this.stopped=true;}};
const micContext={recordStarting:false,micGeneration:0,mic:null,recordAudioSource:'host',recorder:{state:'recording',stop(){this.state='inactive';this.stopped=true;}},recordStream:{getAudioTracks:()=>[recordedMicTrack]},$:id=>micButtons[id],say(){},window:{},navigator:{mediaDevices:{getUserMedia:()=>new Promise(resolve=>releaseMic=()=>{const track={readyState:'live',stop(){this.stopped=true;this.readyState='ended';}};micTracks.push(track);resolve({getTracks:()=>[track],getAudioTracks:()=>[track]});})}}};
vm.runInNewContext('function stopMicrophone()'+microphoneSource,micContext);
const openingMic=micContext.window.connectStudioMicrophone();micButtons['studio-mic-stop'].onclick();releaseMic();await openingMic;assert.equal(micTracks[0].stopped,true);assert.equal(recordedMicTrack.stopped,true);assert.equal(micContext.recorder.stopped,true);assert.equal(micContext.mic,null);
micContext.recordAudioSource='1';micContext.recorder.stopped=false;micContext.recorder.state='recording';recordedMicTrack.stopped=false;
const nextMic=micContext.window.connectStudioMicrophone();releaseMic();await nextMic;micButtons['studio-mic-stop'].onclick();assert.equal(micTracks[1].stopped,true);assert.equal(micContext.recorder.stopped,false);assert.equal(recordedMicTrack.stopped,false);
console.log('PASS microphone off: cancels late permission results, stops host recording clones and preserves recordings using a phone source.');

const recordingStartSource=fs.readFileSync(new URL('../dist/digital-studio.js',import.meta.url),'utf8').split('function cancelRecordingStart(')[1].split('function recording(')[0];
const startButtons={};for(const id of ['studio-record','studio-stop','studio-mode','studio-audio','studio-pause','studio-output-state'])startButtons[id]={value:id==='studio-mode'?'audio':id==='studio-audio'?'host':''};
let permissionComplete,recordSelectedJob='original-job',constructedRecorders=0;const recordingContext={recordStarting:false,recordGeneration:0,recordRequestedMic:false,recorder:null,mic:null,recordJob:null,recordAudioSource:null,recordStream:null,recordStarted:0,pausedAt:0,pausedTotal:0,chunks:[],total:0,active:1,streams:new Map(),screen:null,scene:null,$:id=>startButtons[id],recordSay(){},stopMicrophone(){recordingContext.mic=null;},window:{MediaRecorder:true,currentStudioJob:()=>recordSelectedJob,connectStudioMicrophone:()=>new Promise(resolve=>permissionComplete=()=>{recordingContext.mic={getAudioTracks:()=>[{readyState:'live',clone:()=>({stop(){}})}]};resolve();})},MediaStream:class{constructor(){this.tracks=[];}addTrack(t){this.tracks.push(t);}getTracks(){return this.tracks;}},MediaRecorder:class{constructor(){constructedRecorders++;this.state='inactive';}static isTypeSupported(){return true;}start(){this.state='recording';}stop(){this.state='inactive';}},Date};
vm.runInNewContext('function cancelRecordingStart('+recordingStartSource,recordingContext);
const firstRecordingStart=startButtons['studio-record'].onclick();await startButtons['studio-record'].onclick();assert.equal(recordingContext.recordGeneration,1);assert.equal(startButtons['studio-record'].disabled,true);
recordSelectedJob='new-job';permissionComplete();await firstRecordingStart;assert.equal(recordingContext.recordJob,'original-job');assert.equal(constructedRecorders,1);
recordingContext.recorder=null;recordingContext.mic=null;const cancelledRecordingStart=startButtons['studio-record'].onclick();startButtons['studio-stop'].onclick();permissionComplete();await cancelledRecordingStart;assert.equal(constructedRecorders,1);assert.equal(recordingContext.recordStarting,false);assert.equal(startButtons['studio-record'].disabled,false);
console.log('PASS recording startup: one pending start, original-job snapshot and cancellation without late recorder creation.');
const soundElements={};for(const id of ['studio-sound-meter','studio-sound-status','studio-sound-test','studio-sound-stop','studio-audio'])soundElements[id]={disabled:false,value:'host',addEventListener(name,fn){this[name]=fn;}};
let soundPermissionComplete,soundStream=null,soundContexts=0,soundInterval,resumeSound=null;const soundTrack={readyState:'live'};
const soundContext={document:{getElementById:id=>soundElements[id]},window:{addEventListener(){},studioSelectedAudioStream:()=>soundStream,connectStudioMicrophone:()=>new Promise(resolve=>soundPermissionComplete=()=>{soundStream={getAudioTracks:()=>[soundTrack]};resolve();}),AudioContext:class{constructor(){soundContexts++;this.state='running';}async resume(){if(resumeSound!==null)await new Promise(resolve=>resumeSound=resolve);}async close(){this.closed=true;}createMediaStreamSource(){return {connect(){},disconnect(){}};}createAnalyser(){return {connect(){},disconnect(){},getFloatTimeDomainData(){}};}createGain(){return {gain:{},connect(){},disconnect(){}};}}},MediaStream:class{},Float32Array,audioLevel:()=>({peak:0.5,state:'Good level'}),setInterval:fn=>{soundInterval=fn;return 1;},clearInterval(){soundInterval=null;}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/studio-sound-check.js',import.meta.url),'utf8').split('\n').slice(1).join('\n'),soundContext);
const startingSound=soundElements['studio-sound-test'].onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(soundElements['studio-sound-stop'].disabled,false);await soundElements['studio-sound-stop'].onclick();soundPermissionComplete();await startingSound;assert.equal(soundContexts,0);assert.equal(soundElements['studio-sound-test'].disabled,false);
await soundElements['studio-sound-test'].onclick();assert.equal(soundContexts,1);soundInterval();assert.equal(soundElements['studio-sound-meter'].value,0.5);
await soundElements['studio-audio'].change();assert.equal(soundElements['studio-sound-meter'].value,0);assert.equal(soundInterval,null);
resumeSound=()=>{};const suspendedSound=soundElements['studio-sound-test'].onclick();await new Promise(resolve=>setImmediate(resolve));await soundElements['studio-sound-stop'].onclick();resumeSound();await suspendedSound;assert.equal(soundInterval,null);assert.equal(soundElements['studio-sound-meter'].value,0);
console.log('PASS sound-check cancellation during microphone permission and AudioContext startup; audio source changes stop the meter without delayed restart.');
