import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {digitalStudio} from '../worker/digital-studio.mjs';
import {businessBook} from '../worker/business-book.mjs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../drizzle/0005_elite_ken_ellis.sql',import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};},async batch(list){sqlite.exec('BEGIN');try{const result=[];for(const query of list)result.push(await query.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const req=(path,method='GET',body,user='owner',token)=>new Request('https://studio.test'+path,{method,headers:{origin:'https://studio.test','content-type':'application/json',...(user?{'oai-authenticated-user-id':user}:{}),...(token?{'x-studio-token':token}:{})},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await digitalStudio(req('/api/studio/rooms','POST',null,null),{DB})).status,401);
const response=await digitalStudio(req('/api/studio/rooms','POST'),{DB});assert.equal(response.status,201);const room=await response.json();assert.equal(room.links.length,5);const databaseRoom=sqlite.prepare('SELECT * FROM studio_rooms').get();
for(let slot=1;slot<=5;slot++){const p=new URLSearchParams(new URL(room.links[slot-1]).hash.slice(1)),token=p.get('token');assert(!databaseRoom.tokens.includes(token));const path='/api/studio/rooms/'+room.id+'/signals?slot='+slot;assert.equal((await digitalStudio(req(path,'POST',{event:{type:'offer',sdp:'test offer '+slot}},null,token),{DB})).status,200);assert.equal((await digitalStudio(req(path,'POST',{event:{type:'answer',sdp:'bad'}},null,token),{DB})).status,400);await digitalStudio(req(path,'POST',{slot,event:{type:'answer',sdp:'test answer '+slot}}),{DB});const inbox=await (await digitalStudio(req(path,'GET',null,null,token),{DB})).json();assert.equal(inbox.events.length,1);assert.equal(inbox.events[0].slot,slot);assert.equal((await digitalStudio(req(path.replace('slot='+slot,'slot=6'),'GET',null,null,token),{DB})).status,403);}
const hostEvents=await (await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals'),{DB})).json();assert.equal(hostEvents.events.length,5);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id+'/signals','GET',null,'other-owner'),{DB})).status,403);
assert.equal((await businessBook(req('/api/designer/business-book','POST',{kind:'company',payload:{name:'Bonga Bhengu',description:'Fashion design'}}),{DB})).status,200);assert.equal((await (await businessBook(req('/api/designer/business-book'),{DB})).json()).records.length,1);assert.equal((await (await businessBook(req('/api/designer/business-book','GET',null,'other-owner'),{DB})).json()).records.length,0);
await digitalStudio(req('/api/studio/rooms/'+room.id,'DELETE'),{DB});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_signals').get().n,0);assert.equal((await digitalStudio(req('/api/studio/rooms/'+room.id),{DB})).status,410);
console.log('PASS: five camera invitations, hashed secrets, isolated phone/host signaling, ownership, company persistence, and session cleanup on SQLite. Hardware camera/recording tests still require real devices.');

const vm=await import('node:vm');const phoneElements={};for(const id of ['phone-status','phone-preview','phone-start','phone-stop','phone-facing','phone-audio','phone-title'])phoneElements[id]={value:'environment',checked:false};
const cameraTracks=[];const cameraPeers=[];let releaseCamera=null,cameraDelayed=false,pendingPoll,firstPoll=true;const outgoing=[];
const phoneContext={document:{getElementById:id=>phoneElements[id]},location:{hash:'#room=room&slot=1&token=token'},URLSearchParams,window:{RTCPeerConnection:true,addEventListener(){}},navigator:{mediaDevices:{getUserMedia:async()=>{const track={stop(){this.stopped=true;}};cameraTracks.push(track);const stream={getTracks:()=>[track]};if(cameraDelayed)return new Promise(resolve=>releaseCamera=()=>resolve(stream));return stream;}}},RTCPeerConnection:class{constructor(){this.connectionState='new';cameraPeers.push(this);}addTrack(){}async createOffer(){return {sdp:'offer'};}async setLocalDescription(){}close(){this.closed=true;this.connectionState='closed';this.onconnectionstatechange?.();}},setTimeout:()=>1,clearTimeout(){},fetch:async(url,options)=>{if(options.method==='POST'){outgoing.push(JSON.parse(options.body).event);return {ok:true,json:async()=>({sent:true})};}if(firstPoll){firstPoll=false;return {ok:true,json:async()=>({events:[]})};}return new Promise(resolve=>pendingPoll=()=>resolve({ok:true,json:async()=>({events:[]})}));}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/phone-camera.js',import.meta.url),'utf8'),phoneContext);
await phoneElements['phone-start'].onclick();assert.equal(outgoing[0].type,'offer');const firstPhonePeer=cameraPeers[0];firstPhonePeer.connectionState='failed';firstPhonePeer.onconnectionstatechange();assert.equal(cameraTracks[0].stopped,true);assert.equal(phoneElements['phone-start'].disabled,false);assert.match(phoneElements['phone-status'].textContent,/Reconnect/);
firstPhonePeer.connectionState='connected';firstPhonePeer.onconnectionstatechange();assert.match(phoneElements['phone-status'].textContent,/failed/);pendingPoll();await new Promise(resolve=>setImmediate(resolve));
// Cancel while permission/camera acquisition is pending: late media must be stopped.
phoneContext.fetch=async(url,options)=>({ok:true,json:async()=>({events:[],sent:true})});cameraDelayed=true;const startingPhone=phoneElements['phone-start'].onclick();await new Promise(resolve=>setImmediate(resolve));assert(releaseCamera);await phoneElements['phone-stop'].onclick();releaseCamera();await startingPhone;assert.equal(cameraTracks[1].stopped,true);assert.equal(cameraPeers.length,1);assert.equal(phoneElements['phone-preview'].srcObject,null);
console.log('PASS phone recovery: failed connections release camera, permit reconnect, ignore obsolete callbacks, and stop late camera acquisition after cancellation.');

const localCameraSource=fs.readFileSync(new URL('../dist/digital-studio.js',import.meta.url),'utf8').split('function stopLocal()')[1].split('function stopScreen()')[0];
const localButtons={'studio-local':{},'studio-local-stop':{}};let finishLocal,finishPlayback;const localTracks=[];
const localContext={localGeneration:0,local:null,videos:new Map(),streams:new Map([[1,{phone:true}]]),active:0,nextCamera:0,$:id=>localButtons[id],select(){},say(){},navigator:{mediaDevices:{getUserMedia:()=>new Promise(resolve=>finishLocal=()=>{const track={stop(){this.stopped=true;}};localTracks.push(track);resolve({getTracks:()=>[track],getVideoTracks:()=>[track]});})}},document:{createElement:()=>({pause(){this.paused=true;},play:()=>new Promise(resolve=>finishPlayback=resolve)})}};
vm.runInNewContext('function stopLocal()'+localCameraSource,localContext);
const localStarting=localButtons['studio-local'].onclick();localButtons['studio-local-stop'].onclick();finishLocal();await localStarting;assert.equal(localTracks[0].stopped,true);assert.equal(localContext.streams.has(0),false);assert.equal(localContext.streams.has(1),true);
const secondLocalStart=localButtons['studio-local'].onclick();finishLocal();await new Promise(resolve=>setImmediate(resolve));localButtons['studio-local-stop'].onclick();finishPlayback();await secondLocalStart;assert.equal(localTracks[1].stopped,true);assert.equal(localContext.streams.has(0),false);
const thirdLocalStart=localButtons['studio-local'].onclick();finishLocal();await new Promise(resolve=>setImmediate(resolve));finishPlayback();await thirdLocalStart;assert.equal(localContext.streams.has(0),true);localTracks[2].onended();assert.equal(localContext.streams.has(0),false);assert.equal(localButtons['studio-local'].disabled,false);assert.equal(localContext.streams.has(1),true);
console.log('PASS local camera stop: cancels permission and playback races, releases tracks, recovers ended tracks and preserves phone sources.');
