import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {systemEngine} from '../worker/system-engine.mjs';const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../drizzle',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(result.changes)}};}};},async first(){return sqlite.prepare(sql).get()||null;}};},async batch(queries){sqlite.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};const payload={'zuxuru-fashion-service-v1':{designer:{name:'Bonga'},products:[],evidence:[],orders:[]},'zuxuru-fashion-growth-v1':{partners:[],prospects:[],metrics:[]},'zuxuru-designer-work-v1':{tasks:[],studio:[]}};sqlite.prepare('INSERT INTO designer_workspaces VALUES (?,?,?,?)').run('alice',JSON.stringify(payload),1,new Date().toISOString());const req=(method,user='alice')=>new Request('https://test/api/system/run',{method,headers:{origin:'https://test','oai-authenticated-user-id':user}});const response=await systemEngine(req('POST'),{DB});assert.equal(response.status,200);const report=await response.json();assert(report.steps.some(s=>s.name==='Eight work areas'&&s.status==='Completed'));assert.equal(report.connections.polsia,'Disconnected');assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM system_runs').get().n,1);const saved=JSON.parse(sqlite.prepare('SELECT payload FROM designer_workspaces').get().payload);assert.equal(saved['zuxuru-designer-work-v1'].tasks.length,8);const history=await (await systemEngine(req('GET','bob'),{DB})).json();assert.equal(history.runs.length,0);await systemEngine(req('POST'),{DB});const repeated=JSON.parse(sqlite.prepare('SELECT payload FROM designer_workspaces').get().payload);assert.equal(repeated['zuxuru-designer-work-v1'].tasks.length,8);console.log('PASS shared engine round-trip: health, evidence save, eight work areas, idempotent tasks, isolated run history and blocked providers on SQLite.');

const {studioJobs}=await import('../worker/studio-jobs.mjs');const studioReq=(body,user='alice')=>new Request('https://test/api/studio/jobs',{method:body?'POST':'GET',headers:{origin:'https://test','content-type':'application/json','oai-authenticated-user-id':user},...(body?{body:JSON.stringify(body)}:{})});let jobs=(await (await studioJobs(studioReq(),{DB})).json()).jobs;assert.equal(jobs.length,2);await studioJobs(studioReq({action:'route'}),{DB});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_jobs').get().n,2);const job=jobs[0];assert.equal((await studioJobs(studioReq({action:'stage',id:job.id,revision:1,stage:'Creating'},'bob'),{DB})).status,404);assert.equal((await studioJobs(studioReq({action:'stage',id:job.id,revision:1,stage:'Approved'}),{DB})).status,400);assert.equal((await studioJobs(studioReq({action:'stage',id:job.id,revision:1,stage:'Creating'}),{DB})).status,200);assert.equal((await studioJobs(studioReq({action:'stage',id:job.id,revision:2,stage:'Review'}),{DB})).status,400);sqlite.prepare('INSERT INTO designer_media VALUES (?,?,?,?,?,?,?)').run('asset','alice','key','recording.webm','video/webm',100,new Date().toISOString());assert.equal((await studioJobs(studioReq({action:'attach',id:job.id,revision:2,mediaId:'asset'}),{DB})).status,200);let revision=3;for(const stage of ['Review','Approved','Publish handoff'])assert.equal((await studioJobs(studioReq({action:'stage',id:job.id,revision:revision++,stage}),{DB})).status,200);assert.equal((await studioJobs(studioReq({action:'measure',id:job.id,revision,source:'https://example.com/post',views:100,enquiries:2,sales:1}),{DB})).status,200);jobs=(await (await studioJobs(studioReq(),{DB})).json()).jobs;assert(jobs.find(j=>j.id===job.id).learning);console.log('PASS Studio routing, deduplication, tenant isolation, review gates, owned media attachment and owner-entered measurement learning.');

const settingJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);const settings={caption:'Bonga collection',sponsor:'Confirmed brand',notes:'Show jacket details',layout:'single',brightness:1.2};assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:settingJob.revision,settings}),{DB})).status,200);const restored=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.deepEqual(restored.production,settings);assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:restored.revision,settings:{...settings,brightness:99}}),{DB})).status,400);console.log('PASS persisted production settings and server-side validation.');

const newest=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal((await studioJobs(studioReq({action:'campaign',id:job.id,revision:newest.revision}),{DB})).status,200);const updatedJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);const campaign=sqlite.prepare('SELECT * FROM studio_campaigns WHERE id = ?').get(updatedJob.campaignId);assert.equal(JSON.parse(campaign.payload).sourceStudioJobId,job.id);assert.equal(campaign.status,'Draft');assert.equal(JSON.parse(campaign.payload).approved,false);await studioJobs(studioReq({action:'campaign',id:job.id,revision:updatedJob.revision}),{DB});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_campaigns').get().n,1);console.log('PASS approved Studio-to-campaign handoff, source linkage and duplicate prevention.');

const {clipRange,clipDimensions}=await import('../dist/studio-clip-rules.js');assert.equal(clipRange(0,30,60),'');assert(clipRange(-1,10,60));assert(clipRange(20,10,60));assert(clipRange(0,200,300));assert(clipRange(0,10,Infinity));assert.deepEqual(clipDimensions(1920,1080),[1280,720]);assert.deepEqual(clipDimensions(1080,1920),[720,1280]);console.log('PASS clip duration bounds and portrait/landscape export dimensions.');

const feedbackJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);const nextPayload=JSON.parse(sqlite.prepare('SELECT payload FROM designer_workspaces WHERE user_id = ?').get('alice').payload);assert(nextPayload['zuxuru-designer-work-v1'].tasks.some(t=>t.id===feedbackJob.nextTaskId&&t.sourceStudioJobId===job.id));assert.equal((await studioJobs(studioReq({action:'measure',id:job.id,revision:feedbackJob.revision,source:'https://example.com/post',views:120,enquiries:3,sales:1}),{DB})).status,200);const againPayload=JSON.parse(sqlite.prepare('SELECT payload FROM designer_workspaces WHERE user_id = ?').get('alice').payload);assert.equal(againPayload['zuxuru-designer-work-v1'].tasks.filter(t=>t.id===feedbackJob.nextTaskId).length,1);console.log('PASS measurement-to-daily-work feedback and repeated-result task deduplication.');

let managed=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal((await studioJobs(studioReq({action:'archive',id:job.id,revision:managed.revision,archived:true}),{DB})).status,200);assert(!(await (await studioJobs(studioReq(),{DB})).json()).jobs.some(j=>j.id===job.id));const archivedReq=new Request('https://test/api/studio/jobs?archived=1',{headers:{'oai-authenticated-user-id':'alice'}});managed=(await (await studioJobs(archivedReq,{DB})).json()).jobs.find(j=>j.id===job.id);assert(managed.archived);assert.equal((await studioJobs(studioReq({action:'attach',id:job.id,revision:managed.revision,mediaId:'asset'}),{DB})).status,400);assert.equal((await studioJobs(studioReq({action:'archive',id:job.id,revision:managed.revision,archived:false}),{DB})).status,200);const restoredJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal(restoredJob.mediaIds.length,managed.mediaIds.length);assert(restoredJob.campaignId);console.log('PASS reversible project archive, restoration and preserved media/campaign history.');

const {audioLevel}=await import('../dist/studio-audio-levels.js');assert.equal(audioLevel(new Float32Array(100)).peak,0);assert(audioLevel([0.2,-0.2]).state.includes('present'));assert(audioLevel([1,-1]).state.includes('overload'));assert.equal(audioLevel([NaN]).rms,0);console.log('PASS measured audio level calculation, silence and overload indicators.');

const {studioAnalytics,summarizeStudio}=await import('../worker/studio-analytics.mjs');const statReq=new Request('https://test/api/studio/analytics',{headers:{'oai-authenticated-user-id':'alice'}});const stats=await (await studioAnalytics(statReq,{DB})).json();assert.equal(stats.measuredSources,1);assert.equal(stats.totals.views,120);const otherStats=await (await studioAnalytics(new Request('https://test/api/studio/analytics',{headers:{'oai-authenticated-user-id':'bob'}}),{DB})).json();assert.equal(otherStats.measuredSources,0);const duplicated=summarizeStudio([{id:'a',payload:JSON.stringify({title:'a',measurement:{source:'https://example.com/post?utm_source=test',recordedAt:'2026-10-01',views:5,enquiries:1,sales:0}})},{id:'b',payload:JSON.stringify({title:'b',measurement:{source:'https://example.com/post',recordedAt:'2026-10-02',views:10,enquiries:2,sales:1}})}]);assert.equal(duplicated.measuredSources,1);assert.equal(duplicated.totals.views,10);console.log('PASS private Studio analytics and latest-result deduplication across tracking URLs.');

const presentationJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:presentationJob.revision,settings:{...settings,layout:'presentation',presenter:5}}),{DB})).status,200);const invalidPresenter=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:invalidPresenter.revision,settings:{...settings,layout:'presentation',presenter:6}}),{DB})).status,400);console.log('PASS presentation layout persistence and five-phone presenter validation.');

const vm=await import('node:vm');const attachmentSource=fs.readFileSync(new URL('../dist/studio-jobs.js',import.meta.url),'utf8').split('window.attachStudioMedia=')[1].split(";$('job-select')")[0];const attachmentPosts=[];let missing=false;const ctx={window:{},current:{id:'new-selection'},api:async(body,id)=>{if(!body)return {jobs:missing?[]:[{id,revision:7}]};attachmentPosts.push(body);return {saved:true};},load:async()=>{}};vm.runInNewContext('window.attachStudioMedia='+attachmentSource,ctx);await ctx.window.attachStudioMedia('saved-file','original-job');assert.equal(attachmentPosts[0].id,'original-job');assert.equal(attachmentPosts[0].revision,7);missing=true;await assert.rejects(ctx.window.attachStudioMedia('another-file','missing-job'),/original creative job/);assert.equal(attachmentPosts.length,1);console.log('PASS file attachments retain original job and reject missing targets without fallback.');

const {studioZip,crc32}=await import('../dist/studio-zip.js');assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926);assert.throws(()=>studioZip([{name:'../private',data:'x'}]));const archive=studioZip([{name:'brief.json',data:'{"title":"Bonga"}'},{name:'media/sample.bin',data:new Uint8Array([0,1,2,255])}]);const {tmpdir}=await import('node:os'),{join}=await import('node:path'),{spawnSync}=await import('node:child_process');const testDir=fs.mkdtempSync(join(tmpdir(),'bonga-zip-'));try{const archivePath=join(testDir,'package.zip');fs.writeFileSync(archivePath,new Uint8Array(await archive.arrayBuffer()));const verified=spawnSync('python3',['-c','import sys,zipfile,json;z=zipfile.ZipFile(sys.argv[1]);assert z.testzip() is None;assert json.loads(z.read("brief.json"))["title"]=="Bonga";assert z.read("media/sample.bin")==bytes([0,1,2,255])',archivePath],{encoding:'utf8'});assert.equal(verified.status,0,verified.stderr);}finally{fs.rmSync(testDir,{recursive:true});}console.log('PASS project ZIP export read independently by Python zipfile, CRC validation and path safety.');

const finalJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal((await studioJobs(studioReq({action:'final-media',id:job.id,revision:finalJob.revision,mediaId:'asset'}),{DB})).status,200);const selectedFinal=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);assert.equal(selectedFinal.finalMediaId,'asset');assert.equal(selectedFinal.stage,'Review');assert(selectedFinal.campaignNeedsReview);console.log('PASS final campaign asset selection and review reset after approved-media changes.');
// Remote MCP operates the same D1 records as the signed-in dashboard.
const {businessMcp}=await import('../worker/business-mcp.mjs');
const mcpRequest=(method,params={},user='alice',origin)=>new Request('https://test/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream',...(user?{'oai-authenticated-user-id':user}:{}),...(origin?{origin}:{})},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});
let mcpResult=await (await businessMcp(mcpRequest('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}},null),{DB})).json();
assert.equal(mcpResult.result.serverInfo.name,'Bonga Bhengu business workspace');
mcpResult=await (await businessMcp(mcpRequest('tools/list',{},null),{DB})).json();
assert.equal(mcpResult.result.tools.length,4);
assert.equal((await businessMcp(mcpRequest('tools/call',{name:'bonga_list_work',arguments:{}},null),{DB})).status,401);
assert.equal((await businessMcp(mcpRequest('tools/call',{name:'bonga_list_work',arguments:{}},'alice','https://untrusted.example'),{DB})).status,403);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_list_work',arguments:{}},'bob'),{DB})).json();
assert.equal(mcpResult.result.structuredContent.workspaceExists,false);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_list_work',arguments:{}}),{DB})).json();
assert(mcpResult.result.structuredContent.tasks.length>=8);
assert.equal(mcpResult.result.structuredContent.revision,sqlite.prepare('SELECT revision FROM designer_workspaces WHERE user_id=?').get('alice').revision);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_assign_work',arguments:{confirm:false}}),{DB})).json();
assert(mcpResult.result?.isError||mcpResult.error);
sqlite.prepare('INSERT INTO designer_workspaces VALUES (?,?,?,?)').run('mcp-owner',JSON.stringify(payload),1,new Date().toISOString());
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_assign_work',arguments:{confirm:true}},'mcp-owner'),{DB})).json();
assert.equal(mcpResult.result.structuredContent.added,8);
assert.equal(mcpResult.result.structuredContent.jobsAdded,2);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_list_studio_jobs',arguments:{}},'mcp-owner'),{DB})).json();
assert.equal(mcpResult.result.structuredContent.jobs.length,2);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM studio_jobs WHERE user_id=?').get('bob').n,0);
console.log('PASS authenticated remote MCP: public discovery, private task isolation, origin rejection, shared workspace revision and real Studio handoff.');
const workRevision=sqlite.prepare('SELECT revision FROM designer_workspaces WHERE user_id=?').get('mcp-owner').revision;
const ownedWork=JSON.parse(sqlite.prepare('SELECT payload FROM designer_workspaces WHERE user_id=?').get('mcp-owner').payload)['zuxuru-designer-work-v1'];
const progressArgs={id:ownedWork.tasks[0].id,revision:workRevision,status:'Completed',note:'Owner confirmed the saved offer draft was reviewed.',confirm:true};
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_update_task',arguments:{...progressArgs,note:''}},'mcp-owner'),{DB})).json();
assert(mcpResult.result.isError);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_update_task',arguments:progressArgs},'bob'),{DB})).json();
assert(mcpResult.result.isError);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_update_task',arguments:progressArgs},'mcp-owner'),{DB})).json();
assert.equal(mcpResult.result.structuredContent.revision,workRevision+1);
assert.equal(mcpResult.result.structuredContent.task.done,true);
assert.equal(mcpResult.result.structuredContent.task.progressNote,progressArgs.note);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_update_task',arguments:{...progressArgs,status:'In progress',note:'Old update'}},'mcp-owner'),{DB})).json();
assert(mcpResult.result.isError);
mcpResult=await (await businessMcp(mcpRequest('tools/call',{name:'bonga_list_work',arguments:{}},'mcp-owner'),{DB})).json();
assert.equal(mcpResult.result.structuredContent.tasks[0].status,'Completed');
assert.equal(mcpResult.result.structuredContent.tasks[0].progressNote,progressArgs.note);
assert.equal(mcpResult.result.structuredContent.tasks.length,8);
console.log('PASS shared task progress: owner-only updates, result notes, workspace revision checks and read-back from the dashboard records.');
const queueSource=fs.readFileSync(new URL('../dist/studio-jobs.js',import.meta.url),'utf8');
const queueLoad=queueSource.slice(queueSource.indexOf('async function load(id)'),queueSource.indexOf('function render()'));
const queueElements=Object.fromEntries(['job-select','job-actions','job-brief','job-status'].map(id=>[id,{value:'old-job',replaceChildren(){this.value='';},append(){}}]));
let rendered=0;const queueContext={jobs:[],loadGeneration:0,current:{id:'old-job'},$:id=>queueElements[id],document:{createElement:()=>({})},api:async()=>({jobs:[{id:'owned-job',title:'Real project',stage:'Brief'}]}),render:()=>rendered++};
vm.runInNewContext(queueLoad,queueContext);
assert.equal(await queueContext.load('missing-job'),false);
assert.equal(queueContext.current,undefined);
assert.equal(rendered,0);
assert.equal(await queueContext.load('owned-job'),true);
assert.equal(queueElements['job-select'].value,'owned-job');
assert.equal(rendered,1);
queueContext.api=async()=>{throw Error('Queue unavailable');};
queueContext.current={id:'old-job'};
assert.equal(await queueContext.load('owned-job'),false);
assert.equal(queueContext.current,undefined);
console.log('PASS targeted Studio navigation: exact job selection and no fallback after missing jobs or failed requests.');
const pendingLoads=[];queueContext.api=()=>new Promise((resolve,reject)=>pendingLoads.push({resolve,reject}));
const olderLoad=queueContext.load('older-job'),newerLoad=queueContext.load('newer-job');
pendingLoads[1].resolve({jobs:[{id:'newer-job',title:'Latest selected job',stage:'Brief'}]});
assert.equal(await newerLoad,true);
pendingLoads[0].resolve({jobs:[{id:'older-job',title:'Old request',stage:'Brief'}]});
assert.equal(await olderLoad,false);
assert.equal(queueElements['job-select'].value,'newer-job');
const staleFailure=queueContext.load('failing-job'),latestLoad=queueContext.load('latest-job');
pendingLoads[3].resolve({jobs:[{id:'latest-job',title:'Latest project',stage:'Brief'}]});
assert.equal(await latestLoad,true);
pendingLoads[2].reject(Error('Old request failed'));
assert.equal(await staleFailure,false);
assert.equal(queueElements['job-select'].value,'latest-job');
console.log('PASS Studio load races: delayed responses and failures cannot replace the latest selected project.');
sqlite.prepare('INSERT INTO designer_media VALUES (?,?,?,?,?,?,?)').run('brand-logo','alice','logo-key','brand.png','image/png',50,new Date().toISOString());
sqlite.prepare('INSERT INTO designer_media VALUES (?,?,?,?,?,?,?)').run('foreign-logo','bob','foreign-key','foreign.png','image/png',50,new Date().toISOString());
let logoJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);
assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:logoJob.revision,settings:{...settings,logoMediaId:'foreign-logo'}}),{DB})).status,400);
assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:logoJob.revision,settings:{...settings,logoMediaId:'asset'}}),{DB})).status,400);
assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:logoJob.revision,settings:{...settings,logoMediaId:'brand-logo'}}),{DB})).status,200);
logoJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===job.id);
assert.equal(logoJob.production.logoMediaId,'brand-logo');
assert(!logoJob.mediaIds.includes('brand-logo'),'A branding asset must not become a final campaign deliverable automatically.');
assert.equal((await studioJobs(studioReq({action:'production',id:job.id,revision:logoJob.revision,settings:{...settings,logoMediaId:''}}),{DB})).status,200);
console.log('PASS private Studio logo settings: image ownership, video rejection, persistence and explicit removal.');
const captureElements={};const makeCaptureElement=()=>({children:[],style:{},append(...children){this.children.push(...children);},prepend(...children){this.children.unshift(...children);},remove(){}});
for(const id of ['studio-capture','studio-capture-status','studio-captures'])captureElements[id]=makeCaptureElement();
let finishCapture,selectedCaptureJob='original-capture-job',captureUploads=0;const captureAttachments=[];
const captureContext={window:{currentStudioJob:()=>selectedCaptureJob,captureStudioFrame:()=>new Promise(resolve=>finishCapture=resolve),attachStudioMedia:async(id,jobId)=>{captureAttachments.push({id,jobId});if(captureAttachments.length===1)throw Error('Temporary attachment failure');}},document:{getElementById:id=>captureElements[id],createElement:makeCaptureElement,dispatchEvent(){}},URL:{createObjectURL:()=> 'blob:local-capture',revokeObjectURL(){}},Date,encodeURIComponent,confirm:()=>true,CustomEvent:class{},fetch:async()=>{captureUploads++;return {ok:true,json:async()=>({file:{id:'captured-image',name:'capture.jpg',url:'/api/designer/media/captured-image'}})};}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/studio-capture.js',import.meta.url),'utf8'),captureContext);
const capturing=captureElements['studio-capture'].onclick();selectedCaptureJob='newly-selected-job';finishCapture({type:'image/jpeg'});await capturing;
const captureSave=captureElements['studio-captures'].children[0].children[3];
await captureSave.onclick();await captureSave.onclick();
assert.equal(captureUploads,1);
assert(captureAttachments.every(a=>a.jobId==='original-capture-job'&&a.id==='captured-image'));
console.log('PASS Programme image save: original-job retention during async capture and attachment retry without duplicate upload.');
const mediaReviewJob=(await (await studioJobs(studioReq({action:'create',title:'Media review guard',brief:'Review actual media before handoff'}),{DB})).json()).id;
let guardRevision=1;
await studioJobs(studioReq({action:'attach',id:mediaReviewJob,revision:guardRevision++,mediaId:'asset'}),{DB});
for(const stage of ['Creating','Review','Approved'])assert.equal((await studioJobs(studioReq({action:'stage',id:mediaReviewJob,revision:guardRevision++,stage}),{DB})).status,200);
const guardedCampaign=(await (await studioJobs(studioReq({action:'campaign',id:mediaReviewJob,revision:guardRevision++}),{DB})).json()).campaignId;
sqlite.prepare("UPDATE studio_campaigns SET payload=json_set(payload,'$.approved',json('true')),status='Approved draft — not scheduled' WHERE id=?").run(guardedCampaign);
const unchangedAttach=await studioJobs(studioReq({action:'attach',id:mediaReviewJob,revision:guardRevision++,mediaId:'asset'}),{DB});assert.equal(unchangedAttach.status,200);
let guardJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===mediaReviewJob);
assert.equal(guardJob.stage,'Publish handoff');
const changedAttach=await studioJobs(studioReq({action:'attach',id:mediaReviewJob,revision:guardRevision++,mediaId:'brand-logo'}),{DB});
assert.equal((await changedAttach.json()).reviewRequired,true);
guardJob=(await (await studioJobs(studioReq(),{DB})).json()).jobs.find(j=>j.id===mediaReviewJob);
assert.equal(guardJob.stage,'Review');assert.equal(guardJob.campaignNeedsReview,true);
const invalidated=sqlite.prepare('SELECT payload,status FROM studio_campaigns WHERE id=?').get(guardedCampaign);
assert.equal(JSON.parse(invalidated.payload).approved,false);
assert(invalidated.status.startsWith('Draft'));
assert.equal((await studioJobs(studioReq({action:'attach',id:mediaReviewJob,revision:guardRevision-2,mediaId:'brand-logo'}),{DB})).status,409);
console.log('PASS new media review: duplicate attachments preserve approval; changed media resets job and linked campaign approval atomically.');
const {studioCampaigns}=await import('../worker/studio-campaigns.mjs');
const campaignReviewRequest=approved=>new Request('https://test/api/studio/campaigns',{method:'POST',headers:{origin:'https://test','content-type':'application/json','oai-authenticated-user-id':'alice'},body:JSON.stringify({id:guardedCampaign,payload:{title:'Review linked campaign',posts:[{platform:'Facebook',caption:'Owner-reviewed caption',mediaId:''}],approved}})});
assert.equal((await studioCampaigns(campaignReviewRequest(true),{DB})).status,409);
assert.equal((await studioCampaigns(campaignReviewRequest(false),{DB})).status,200);
assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM studio_campaigns WHERE id=?').get(guardedCampaign).payload).sourceStudioJobId,mediaReviewJob);
assert.equal((await studioJobs(studioReq({action:'stage',id:mediaReviewJob,revision:guardRevision++,stage:'Approved'}),{DB})).status,200);
assert.equal((await studioCampaigns(campaignReviewRequest(true),{DB})).status,200);
console.log('PASS linked campaign approval requires current Studio approval and retains its source job when an editor omits the link.');

const changeSource=queueSource.split('async function change(body')[1].split('window.openStudioJob=')[0];
const progressPosts=[];const progressLoads=[];const progressContext={current:{id:'new-job',revision:99},window:{},$:()=>({}),api:async body=>{progressPosts.push(body);return {};},load:async id=>progressLoads.push(id)};progressContext.window.top=progressContext.window;
vm.runInNewContext('async function change(body'+changeSource,progressContext);
await progressContext.change({action:'edit',title:'Original title'},{id:'original-job',revision:7});
assert.equal(progressPosts[0].id,'original-job');assert.equal(progressPosts[0].revision,7);assert.equal(progressLoads[0],'new-job');
await progressContext.change({action:'measure',views:1},{id:'measurement-job',revision:8});
assert.equal(progressPosts[1].id,'measurement-job');assert.equal(progressPosts[1].revision,8);
console.log('PASS delayed edits and results keep their original job and revision without changing the current selection.');

const reviewElement=tag=>({tag,children:[],listeners:{},append(...items){this.children.push(...items);},replaceChildren(){this.children=[];this.textContent='';},addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);},querySelectorAll(){return this.children.flatMap(c=>[...(['video','audio'].includes(c.tag)?[c]:[]),...c.querySelectorAll()]);},pause(){this.paused=true;}});
const reviewContext={window:{},document:{createElement:reviewElement},fetch:async url=>{assert.equal(url,'/api/designer/media');return {ok:true,json:async()=>({files:[{id:'image/1',name:'<b>Actual image</b>',content_type:'image/jpeg'},{id:'video',name:'Film.webm',content_type:'video/webm'},{id:'audio',name:'Podcast.webm',content_type:'audio/webm'}]})};},encodeURIComponent};
vm.runInNewContext(fs.readFileSync(new URL('../dist/studio-review.js',import.meta.url),'utf8'),reviewContext);
const reviewDetails=reviewElement('details');const finalSelections=[];const reviewJob={id:'original',revision:3,mediaIds:['image/1','video','audio','deleted'],finalMediaId:'video'};
reviewContext.window.addStudioMediaReview(reviewDetails,reviewJob,(id,target)=>finalSelections.push({id,target}));
const reviewPanel=reviewDetails.children[0];assert.equal(reviewPanel.children.length,0);reviewDetails.open=true;for(const fn of reviewDetails.listeners.toggle)await fn();
assert.equal(reviewPanel.children.length,4);assert.equal(reviewPanel.children[0].children[0].textContent,'<b>Actual image</b>');
assert.equal(reviewPanel.children[0].children[1].src,'/api/designer/media/image%2F1');
const previewVideo=reviewPanel.children[1].children[1];assert.equal(previewVideo.controls,true);assert.equal(previewVideo.preload,'metadata');assert.equal(previewVideo.autoplay,undefined);
assert.equal(reviewPanel.children[1].children.at(-1).disabled,true);assert.equal(reviewPanel.children[2].children.at(-1).tag,'a');
reviewPanel.children[0].children.at(-1).onclick();assert.equal(finalSelections[0].target.id,'original');assert.equal(finalSelections[0].target.revision,3);
reviewDetails.open=false;for(const fn of reviewDetails.listeners.toggle)await fn();assert.equal(previewVideo.paused,true);
let reviewAttempts=0;reviewContext.fetch=async()=>{reviewAttempts++;if(reviewAttempts===1)throw Error('Offline');return {ok:true,json:async()=>({files:[]})};};
const retryDetails=reviewElement('details');reviewContext.window.addStudioMediaReview(retryDetails,reviewJob,()=>{});retryDetails.open=true;for(const fn of retryDetails.listeners.toggle)await fn();assert.equal(retryDetails.children[0].textContent,'Offline');for(const fn of retryDetails.listeners.toggle)await fn();assert.equal(reviewAttempts,2);
console.log('PASS private media review: lazy previews, safe names, missing assets, original-job final selection, no autoplay, playback pause and retry.');

const reviewEdits=[];reviewContext.document.dispatchEvent=event=>reviewEdits.push(event);reviewContext.CustomEvent=class{constructor(type,options){this.type=type;this.detail=options.detail;}};
reviewPanel.children[0].children.find(x=>x.textContent==='Edit image').onclick();
reviewPanel.children[1].children.find(x=>x.textContent==='Trim video').onclick();
assert.equal(reviewEdits[0].type,'media-edit-image');assert.equal(reviewEdits[0].detail.studioJobId,'original');assert.equal(reviewEdits[0].detail.url,'/api/designer/media/image%2F1');
assert.equal(reviewEdits[1].type,'media-edit-video');assert.equal(reviewEdits[1].detail.studioJobId,'original');assert.equal(previewVideo.paused,true);
reviewContext.fetch=async()=>({ok:true,json:async()=>({files:[{id:'video',name:'Film.webm',content_type:'video/webm'}]})});
const archivedReview=reviewElement('details');reviewContext.window.addStudioMediaReview(archivedReview,{...reviewJob,archived:true},()=>{});archivedReview.open=true;for(const fn of archivedReview.listeners.toggle)await fn();
assert.equal(archivedReview.children[0].children[1].children.some(x=>x.textContent==='Trim video'),false);
console.log('PASS review-to-editor handoff: original project, canonical private media URLs, paused playback and no archive editing.');

const imageEditorElements={};for(const id of ['image-edit-dialog','image-edit-canvas','image-edit-status','image-edit-zoom','image-edit-ratio','image-edit-rotate','image-edit-close','image-edit-save','studio-media-status'])imageEditorElements[id]={addEventListener(){}};
imageEditorElements['image-edit-dialog'].showModal=function(){this.open=true;};imageEditorElements['image-edit-dialog'].close=function(){this.open=false;};
imageEditorElements['image-edit-canvas'].getContext=()=>({fillRect(){},translate(){},scale(){},rotate(){},drawImage(){}});
const requestedImages=[],imageEditorListeners={};const imageEditorContext={window:{},document:{getElementById:id=>imageEditorElements[id],addEventListener:(name,fn)=>imageEditorListeners[name]=fn},Image:class{constructor(){this.width=100;this.height=100;requestedImages.push(this);}}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/studio-image-editor.js',import.meta.url),'utf8'),imageEditorContext);
imageEditorListeners['media-edit-image']({detail:{name:'Original.jpg',url:'/api/designer/media/original',studioJobId:'original-job'}});
imageEditorListeners['media-edit-image']({detail:{name:'Another.jpg',url:'/api/designer/media/another'}});assert.equal(requestedImages.length,1);
requestedImages[0].onload();assert.equal(imageEditorElements['image-edit-dialog'].open,true);
imageEditorListeners['media-edit-image']({detail:{name:'Another.jpg',url:'/api/designer/media/another'}});assert.equal(requestedImages.length,1);
imageEditorElements['image-edit-close'].onclick();imageEditorListeners['media-edit-image']({detail:{name:'Another.jpg',url:'/api/designer/media/another'}});assert.equal(requestedImages.length,2);
requestedImages[1].onerror();imageEditorListeners['media-edit-image']({detail:{name:'Retry.jpg',url:'/api/designer/media/retry'}});assert.equal(requestedImages.length,3);
console.log('PASS image editor prevents overlapping loads and open edits, and permits retry after an image loading failure.');

imageEditorElements['studio-media-refresh']={click(){}};
requestedImages[2].onload();let editedUploads=0,editedExports=0;const editedAttachments=[];
imageEditorElements['image-edit-canvas'].toBlob=callback=>{editedExports++;callback({type:'image/jpeg'});};
imageEditorContext.fetch=async()=>{editedUploads++;return {ok:true,json:async()=>({file:{id:'edited-copy'}})};};
imageEditorContext.encodeURIComponent=encodeURIComponent;
imageEditorContext.window.attachStudioMedia=async(id,jobId)=>{editedAttachments.push({id,jobId});if(editedAttachments.length===1)throw Error('Temporary attachment error');};
// Load an actual job-linked image before testing its save/retry path.
imageEditorElements['image-edit-close'].onclick();imageEditorListeners['media-edit-image']({detail:{name:'Original.jpg',url:'/api/designer/media/original',studioJobId:'original-job'}});requestedImages[3].onload();
await imageEditorElements['image-edit-save'].onclick();assert.equal(imageEditorElements['image-edit-dialog'].open,true);assert.equal(imageEditorElements['image-edit-save'].textContent,'Retry job attachment');assert.equal(imageEditorElements['image-edit-rotate'].disabled,true);
await imageEditorElements['image-edit-save'].onclick();assert.equal(editedUploads,1);assert.equal(editedExports,1);assert.equal(editedAttachments.length,2);assert(editedAttachments.every(x=>x.id==='edited-copy'&&x.jobId==='original-job'));assert.equal(imageEditorElements['image-edit-dialog'].open,false);
console.log('PASS image attachment retry reuses one exported/uploaded copy and retains the original creative job.');
const serviceTabs=Array.from({length:3},()=>({listeners:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,fn){this.listeners[k]=fn;},focus(){this.focused=true;}})),servicePanels=Array.from({length:3},()=>({hidden:false})),workspaceGoal={value:''},workspaceListeners={};
const workspaceContext={document:{addEventListener:(k,fn)=>workspaceListeners[k]=fn,getElementById:id=>id==='workspace-layer'?{querySelectorAll:selector=>selector==='[role="tab"]'?serviceTabs:servicePanels,addEventListener:(k,fn)=>workspaceListeners[k]=fn}:workspaceGoal}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/workspace-layer.js',import.meta.url),'utf8'),workspaceContext);
assert.deepEqual(servicePanels.map(p=>p.hidden),[false,true,true]);serviceTabs[2].listeners.click();assert.deepEqual(servicePanels.map(p=>p.hidden),[false,false,false]);assert.equal(serviceTabs[2].attributes['aria-selected'],'true');
serviceTabs[2].listeners.keydown({key:'ArrowRight',preventDefault(){}});assert.deepEqual(servicePanels.map(p=>p.hidden),[false,true,true]);assert.equal(serviceTabs[0].focused,true);
workspaceListeners.click({target:{closest:()=>({dataset:{workspaceBrief:'Rental enquiry'}})}});assert.equal(workspaceGoal.value,'Rental enquiry');
console.log('PASS integrated workspace service tiers: cumulative modules, keyboard navigation, accessible selection and existing brief form handoff.');
const motionObservers=[],motionListeners={},motionVideoListeners={},motionButtonListeners={},motionPreference={matches:false,addEventListener(name,fn){this.change=fn;}};let bannerPlays=0;
const motionVideo={paused:true,muted:true,volume:1,addEventListener:(name,fn)=>motionVideoListeners[name]=fn,play(){bannerPlays++;this.paused=false;motionVideoListeners.play?.();return Promise.resolve();},pause(){this.paused=true;motionVideoListeners.pause?.();}},motionButton={addEventListener:(name,fn)=>motionButtonListeners[name]=fn};
const motionSoundListeners={},motionSound={attributes:{},addEventListener:(name,fn)=>motionSoundListeners[name]=fn,setAttribute(k,v){this.attributes[k]=v;}};
const motionContext={matchMedia:()=>motionPreference,document:{hidden:false,querySelectorAll:()=>[],getElementById:id=>id==='workspace-ad-video'?motionVideo:id==='workspace-ad-sound'?motionSound:id==='workspace-ad-toggle'?motionButton:null,addEventListener:(name,fn)=>motionListeners[name]=fn},window:{IntersectionObserver:true},IntersectionObserver:class{constructor(fn){this.notify=fn;motionObservers.push(this);}observe(){}},requestAnimationFrame(){},cancelAnimationFrame(){}};
vm.runInNewContext(fs.readFileSync(new URL('../dist/lookbook-motion.js',import.meta.url),'utf8'),motionContext);
motionObservers[1].notify([{isIntersecting:true}]);assert.equal(bannerPlays,1);motionButtonListeners.click();assert.equal(motionVideo.paused,true);motionObservers[1].notify([{isIntersecting:false}]);motionObservers[1].notify([{isIntersecting:true}]);assert.equal(bannerPlays,1);
motionButtonListeners.click();assert.equal(bannerPlays,2);motionContext.document.hidden=true;motionListeners.visibilitychange();assert.equal(motionVideo.paused,true);motionPreference.matches=true;motionPreference.change();assert.equal(motionVideo.paused,true);
console.log('PASS banner playback respects visibility, manual pause and reduced motion, without sending an advertising enquiry.');

assert.equal(motionSound.attributes['aria-pressed'],'false');motionSoundListeners.click();assert.equal(motionVideo.muted,false);assert.equal(motionSound.attributes['aria-pressed'],'true');motionVideo.pause();const nativePauseCount=bannerPlays;motionObservers[1].notify([{isIntersecting:false}]);motionObservers[1].notify([{isIntersecting:true}]);assert.equal(bannerPlays,nativePauseCount);motionVideo.volume=0;motionVideoListeners.volumechange();assert.equal(motionSound.attributes['aria-pressed'],'false');motionSoundListeners.click();assert.equal(motionVideo.muted,false);assert.equal(motionVideo.volume,1);console.log('PASS uploaded banner audio: explicit sound activation, native pause persistence and recovery from native zero volume.');
