import {routeStudioTasks} from './studio-jobs.mjs';
import {designerLive} from './designer-live.mjs';
import {designerStore} from './designer-store.mjs';
import {designerInvestigate} from './designer-investigate.mjs';
import {designerEngine} from './designer-engine.mjs';
import {designerData} from './designer-data.mjs';
const systemJSON=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
export async function systemEngine(request,env){const user=request.headers.get('oai-authenticated-user-id'),url=new URL(request.url);if(!user)return systemJSON({error:'Sign in to run your business system.'},401);if(!env.DB)return systemJSON({error:'Business system storage unavailable.'},503);if(request.method==='GET'){try{const rows=await env.DB.prepare('SELECT id,report,created_at FROM system_runs WHERE user_id = ? ORDER BY created_at DESC LIMIT 20').bind(user).all();return systemJSON({runs:(rows.results||[]).map(r=>({id:r.id,createdAt:r.created_at,...JSON.parse(r.report)}))});}catch{return systemJSON({error:'System history unavailable'},503);}}if(request.method!=='POST'||request.headers.get('origin')!==url.origin)return systemJSON({error:'Open your dashboard to run this system.'},403);const runId=crypto.randomUUID(),started=new Date().toISOString(),steps=[];function sub(path,method='GET',body){const headers=new Headers(request.headers);headers.delete('content-length');headers.set('content-type','application/json');return new Request(url.origin+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})});}async function call(name,fn,path,method='GET'){try{const r=await fn(sub(path,method),env),data=await r.json();if(!r.ok)throw Error(data.error||'Service unavailable');steps.push({name,status:'Completed'});return data;}catch(e){steps.push({name,status:'Failed',message:e.message});return null;}}async function update(mutate){const r=await designerData(sub('/api/designer/workspace'),env),s=await r.json();if(!r.ok||!s.payload)throw Error('Save your designer workspace first.');mutate(s.payload);const out=await designerData(sub('/api/designer/workspace','PUT',{revision:s.revision,payload:s.payload}),env),d=await out.json();if(!out.ok)throw Error(d.error);}
const health=await call('System health',designerLive,'/api/designer/health');const store=await call('Hosted storefront',designerStore,'/api/designer/storefront');const enquiries=await call('Customer enquiries',designerStore,'/api/designer/enquiries');if(enquiries){try{let added=0;await update(payload=>{const base=payload['zuxuru-fashion-service-v1'];for(const e of enquiries.enquiries||[]){if(base.orders.length>=500)break;if(!base.orders.some(o=>o.id===e.id)){base.orders.push({id:e.id,customer:e.name,request:e.product,next:e.message+' · Reply to: '+e.contact,stage:'Enquiry',due:''});added++;}}});steps.push({name:'Sales flow',status:'Completed',added});}catch(e){steps.push({name:'Sales flow',status:'Failed',message:e.message});}}
const evidence=await call('Evidence investigation',designerInvestigate,'/api/designer/investigate','POST');if(evidence){try{await update(p=>{p['zuxuru-fashion-service-v1'].evidenceChecks=evidence.results||[];});steps.push({name:'Evidence saved',status:'Completed',checked:(evidence.results||[]).length});}catch(e){steps.push({name:'Evidence saved',status:'Failed',message:e.message});}}
const work=await call('Eight work areas',designerEngine,'/api/designer/engine','POST');if(work)steps[steps.length-1].tasksAdded=work.added;try{steps.push({name:'Creative Studio handoff',status:'Completed',jobsAdded:await routeStudioTasks(env,user)});}catch{steps.push({name:'Creative Studio handoff',status:'Failed',message:'Creative job queue unavailable'});}let campaigns=0;try{campaigns=(await env.DB.prepare('SELECT COUNT(*) AS total FROM studio_campaigns WHERE user_id = ?').bind(user).first()).total;}catch{}steps.push({name:'Platform campaigns',status:'Blocked',drafts:campaigns,message:'Polsia disconnected; social publishing authorization required. No campaigns scheduled or posted.'});const report={status:steps.some(s=>s.status==='Failed')?'Needs attention':'Connected work completed; external services blocked',steps,connections:{polsia:'Disconnected',socialPublishing:'Authorization required',ai:health?.ai||'Unavailable'},storefrontPublished:!!store?.url,notice:'This run checks saved sources, imports real enquiries and assigns proposed tasks. It does not run AI inference, publish content, charge payments, place production orders or book couriers.'};try{await env.DB.prepare('INSERT INTO system_runs (id,user_id,report,created_at) VALUES (?,?,?,?)').bind(runId,user,JSON.stringify(report),started).run();}catch{return systemJSON({id:runId,...report,error:'Actions may have completed, but the shared run history could not be saved. Reload your records before retrying.'},503);}return systemJSON({id:runId,...report});}
